[
{"word":"dog","phonetic":"/d??g/","pos":"n.","meaning":"狗","sentence":"The dog is barking loudly.","translation":"那只狗叫得很大声。"},
{"word":"cat","phonetic":"/k?t/","pos":"n.","meaning":"猫","sentence":"The cat is sleeping on the sofa.","translation":"猫正在沙发上睡觉。"},
{"word":"you","phonetic":"/ju?/","pos":"pron.","meaning":"你;你们","sentence":"Nice to meet you.","translation":"很高兴见到你。"},
{"word":"I","phonetic":"/a?/","pos":"pron.","meaning":"我","sentence":"I am a student.","translation":"我是一名学生。"},
{"word":"your","phonetic":"/j??r/","pos":"pron.","meaning":"你的;你们的","sentence":"What is your name?","translation":"你叫什么名字？"},
{"word":"my","phonetic":"/ma?/","pos":"pron.","meaning":"我的","sentence":"This is my book.","translation":"这是我的书。"},
{"word":"Chinese","phonetic":"/?t?a??ni?z/","pos":"n., adj.","meaning":"中文;中国人;中国的","sentence":"He speaks Chinese very well.","translation":"他中文说得很好。"},
{"word":"English","phonetic":"/???gl??/","pos":"n., adj.","meaning":"英语;英国人;英语的","sentence":"I am learning English.","translation":"我正在学英语。"},
{"word":"teacher","phonetic":"/?ti?t??r/","pos":"n.","meaning":"教师","sentence":"She is a math teacher.","translation":"她是一位数学老师。"},
{"word":"mother","phonetic":"/?m?e?r/","pos":"n.","meaning":"母亲","sentence":"My mother cooks dinner every day.","translation":"我妈妈每天做晚饭。"},
{"word":"father","phonetic":"/?fɑ?e?r/","pos":"n.","meaning":"父亲","sentence":"His father works in a bank.","translation":"他父亲在银行工作。"},
{"word":"student","phonetic":"/?stu?d?nt/","pos":"n.","meaning":"学生","sentence":"He is a diligent student.","translation":"他是个勤奋的学生。"},
{"word":"book","phonetic":"/b?k/","pos":"n.","meaning":"书","sentence":"I like reading this book.","translation":"我喜欢读这本书。"},
{"word":"and","phonetic":"/?nd/","pos":"conj.","meaning":"和;与","sentence":"I like apples and bananas.","translation":"我喜欢苹果和香蕉。"},
{"word":"like","phonetic":"/la?k/","pos":"v., prep.","meaning":"喜欢;像","sentence":"Do you like coffee?","translation":"你喜欢咖啡吗？"},
{"word":"we","phonetic":"/wi?/","pos":"pron.","meaning":"我们","sentence":"We are friends.","translation":"我们是朋友。"},
{"word":"our","phonetic":"/?a??r/","pos":"pron.","meaning":"我们的","sentence":"This is our house.","translation":"这是我们的房子。"},
{"word":"they","phonetic":"/ee?/","pos":"pron.","meaning":"他们","sentence":"They are playing soccer.","translation":"他们正在踢足球。"},
{"word":"their","phonetic":"/eer/","pos":"pron.","meaning":"他们的","sentence":"Their car is new.","translation":"他们的车是新的。"},
{"word":"black","phonetic":"/bl?k/","pos":"adj., n.","meaning":"黑色的;黑色","sentence":"He is wearing a black suit.","translation":"他穿着一套黑色西装。"},
{"word":"blue","phonetic":"/blu?/","pos":"adj., n.","meaning":"蓝色的;蓝色","sentence":"The sky is blue today.","translation":"今天天空是蓝色的。"},
{"word":"white","phonetic":"/wa?t/","pos":"adj., n.","meaning":"白色的;白色","sentence":"She has a white cat.","translation":"她有一只白猫。"},
{"word":"red","phonetic":"/red/","pos":"adj., n.","meaning":"红色的;红色","sentence":"Apples are red.","translation":"苹果是红色的。"},
{"word":"green","phonetic":"/gri?n/","pos":"adj., n.","meaning":"绿色的;绿色","sentence":"The grass is green.","translation":"草是绿色的。"},
{"word":"computer","phonetic":"/k?m?pju?t?r/","pos":"n.","meaning":"电脑","sentence":"I use a computer for work.","translation":"我用电脑工作。"},
{"word":"room","phonetic":"/ru?m/","pos":"n.","meaning":"房间","sentence":"My room is very clean.","translation":"我的房间很干净。"},
{"word":"phone","phonetic":"/fo?n/","pos":"n.","meaning":"电话","sentence":"Can I use your phone?","translation":"我能用一下你的电话吗？"},
{"word":"big","phonetic":"/b?g/","pos":"adj.","meaning":"大的","sentence":"That is a big house.","translation":"那是所大房子。"},
{"word":"house","phonetic":"/ha?s/","pos":"n.","meaning":"房子","sentence":"They live in a big house.","translation":"他们住在一所大房子里。"},
{"word":"small","phonetic":"/sm??l/","pos":"adj.","meaning":"小的","sentence":"The shirt is too small for me.","translation":"这件衬衫对我来说太小了。"},
{"word":"short","phonetic":"/???rt/","pos":"adj.","meaning":"短的;矮的","sentence":"He has short hair.","translation":"他留着短发。"},
{"word":"long","phonetic":"/l???/","pos":"adj.","meaning":"长的","sentence":"It's a long story.","translation":"这是一个很长的故事。"},
{"word":"spring","phonetic":"/spr??/","pos":"n.","meaning":"春天","sentence":"Flowers bloom in spring.","translation":"花儿在春天开放。"},
{"word":"summer","phonetic":"/?s?m?r/","pos":"n.","meaning":"夏天","sentence":"It is hot in summer.","translation":"夏天很热。"},
{"word":"fall","phonetic":"/f??l/","pos":"n., v.","meaning":"秋天;跌倒","sentence":"Leaves turn yellow in the fall.","translation":"树叶在秋天变黄。"},
{"word":"winter","phonetic":"/?w?nt?r/","pos":"n.","meaning":"冬天","sentence":"Do you like winter?","translation":"你喜欢冬天吗？"},
{"word":"is","phonetic":"/?z/","pos":"v.","meaning":"是(be的第三人称单数)","sentence":"He is my brother.","translation":"他是我的哥哥。"},
{"word":"or","phonetic":"/??r/","pos":"conj.","meaning":"或者","sentence":"Tea or coffee?","translation":"茶还是咖啡？"},
{"word":"more","phonetic":"/m??r/","pos":"adj., adv.","meaning":"更多的","sentence":"I need more time.","translation":"我需要更多时间。"},
{"word":"less","phonetic":"/les/","pos":"adj., adv.","meaning":"较少的","sentence":"Eat less sugar.","translation":"少吃糖。"},
{"word":"hot","phonetic":"/hɑ?t/","pos":"adj.","meaning":"热的","sentence":"The soup is very hot.","translation":"汤很烫。"},
{"word":"cold","phonetic":"/ko?ld/","pos":"adj.","meaning":"冷的","sentence":"It is cold outside.","translation":"外面很冷。"},
{"word":"coffee","phonetic":"/?k??fi/","pos":"n.","meaning":"咖啡","sentence":"I drink coffee every morning.","translation":"我每天早上喝咖啡。"},
{"word":"juice","phonetic":"/d?u?s/","pos":"n.","meaning":"果汁","sentence":"Orange juice is delicious.","translation":"橙汁很好喝。"},
{"word":"drink","phonetic":"/dr??k/","pos":"v., n.","meaning":"喝;饮料","sentence":"Drink plenty of water.","translation":"多喝水。"},
{"word":"water","phonetic":"/?w??t?r/","pos":"n.","meaning":"水","sentence":"Can I have some water?","translation":"能给我点水吗？"},
{"word":"tea","phonetic":"/ti?/","pos":"n.","meaning":"茶","sentence":"Would you like some tea?","translation":"你想喝点茶吗？"},
{"word":"yes","phonetic":"/jes/","pos":"adv.","meaning":"是;对","sentence":"Yes, I agree.","translation":"是的，我同意。"},
{"word":"a","phonetic":"/?/","pos":"art.","meaning":"一个","sentence":"I have a pen.","translation":"我有一支笔。"},
{"word":"are","phonetic":"/ɑ?r/","pos":"v.","meaning":"是(be的复数/第二人称)","sentence":"You are helpful.","translation":"你很乐于助人。"},
{"word":"am","phonetic":"/?m/","pos":"v.","meaning":"是(be的第一人称单数)","sentence":"I am ready.","translation":"我准备好了。"},
{"word":"hello","phonetic":"/h??lo?/","pos":"int.","meaning":"你好","sentence":"Hello, how are you?","translation":"你好，你好吗？"},
{"word":"good","phonetic":"/g?d/","pos":"adj.","meaning":"好的","sentence":"Have a good day.","translation":"祝你有美好的一天。"},
{"word":"he","phonetic":"/hi?/","pos":"pron.","meaning":"他","sentence":"He is a doctor.","translation":"他是一名医生。"},
{"word":"she","phonetic":"/?i?/","pos":"pron.","meaning":"她","sentence":"She is reading.","translation":"她正在读书。"},
{"word":"woman","phonetic":"/?w?m?n/","pos":"n.","meaning":"女人","sentence":"That woman is my aunt.","translation":"那个女人是我阿姨。"},
{"word":"girl","phonetic":"/g??rl/","pos":"n.","meaning":"女孩","sentence":"The girl is singing.","translation":"那个女孩正在唱歌。"},
{"word":"man","phonetic":"/m?n/","pos":"n.","meaning":"男人","sentence":"The man is tall.","translation":"那个男人很高。"},
{"word":"boy","phonetic":"/b??/","pos":"n.","meaning":"男孩","sentence":"The boy is playing with a ball.","translation":"那个男孩正在玩球。"},
{"word":"evening","phonetic":"/?i?vn??/","pos":"n.","meaning":"晚上;傍晚","sentence":"Good evening!","translation":"晚上好！"},
{"word":"morning","phonetic":"/?m??rn??/","pos":"n.","meaning":"早晨","sentence":"I run in the morning.","translation":"我在早晨跑步。"},
{"word":"look","phonetic":"/l?k/","pos":"v.","meaning":"看","sentence":"Look at the picture.","translation":"看这张图片。"},
{"word":"bag","phonetic":"/b?g/","pos":"n.","meaning":"包","sentence":"Where is my bag?","translation":"我的包在哪里？"},
{"word":"by","phonetic":"/ba?/","pos":"prep.","meaning":"通过;被;在旁边","sentence":"I go to work by bus.","translation":"我乘公交车上班。"},
{"word":"this","phonetic":"/e?s/","pos":"pron., adj.","meaning":"这;这个","sentence":"This is my friend.","translation":"这是我的朋友。"},
{"word":"thanks","phonetic":"/θ??ks/","pos":"int., n.","meaning":"谢谢","sentence":"Thanks for your help.","translation":"谢谢你的帮助。"},
{"word":"road","phonetic":"/ro?d/","pos":"n.","meaning":"路","sentence":"Be careful crossing the road.","translation":"过马路要小心。"},
{"word":"coat","phonetic":"/ko?t/","pos":"n.","meaning":"外套","sentence":"Put on your coat.","translation":"穿上你的外套。"},
{"word":"watch","phonetic":"/wɑ?t?/","pos":"v., n.","meaning":"观看;手表","sentence":"I watch TV every night.","translation":"我每天晚上看电视。"},
{"word":"no","phonetic":"/no?/","pos":"adv., adj.","meaning":"不;没有","sentence":"No, thank you.","translation":"不，谢谢。"},
{"word":"wallet","phonetic":"/?wɑ?l?t/","pos":"n.","meaning":"钱包","sentence":"I lost my wallet.","translation":"我丢了钱包。"},
{"word":"not","phonetic":"/nɑ?t/","pos":"adv.","meaning":"不","sentence":"I am not tired.","translation":"我不累。"},
{"word":"camera","phonetic":"/?k?m?r?/","pos":"n.","meaning":"相机","sentence":"This camera is expensive.","translation":"这台相机很贵。"},
{"word":"wall","phonetic":"/w??l/","pos":"n.","meaning":"墙","sentence":"The picture is on the wall.","translation":"画在墙上。"},
{"word":"excuse me","phonetic":"/?k?skju?z mi?/","pos":"phrase","meaning":"打扰一下;借过","sentence":"Excuse me, where is the restroom?","translation":"打扰一下，洗手间在哪里？"},
{"word":"at","phonetic":"/?t/","pos":"prep.","meaning":"在","sentence":"I am at home.","translation":"我在家。"},
{"word":"new","phonetic":"/nu?/","pos":"adj.","meaning":"新的","sentence":"I have a new phone.","translation":"我有一部新手机。"},
{"word":"nice","phonetic":"/na?s/","pos":"adj.","meaning":"美好的;友好的","sentence":"Have a nice day.","translation":"祝你有美好的一天。"},
{"word":"from","phonetic":"/fr?m/","pos":"prep.","meaning":"来自;从","sentence":"I am from China.","translation":"我来自中国。"},
{"word":"meat","phonetic":"/mi?t/","pos":"n.","meaning":"肉","sentence":"He doesn't eat meat.","translation":"他不吃肉。"},
{"word":"land","phonetic":"/l?nd/","pos":"n., v.","meaning":"陆地;着陆","sentence":"The plane will land soon.","translation":"飞机很快就要着陆了。"},
{"word":"China","phonetic":"/?t?a?n?/","pos":"n.","meaning":"中国","sentence":"China is a big country.","translation":"中国是一个大国。"},
{"word":"speak","phonetic":"/spi?k/","pos":"v.","meaning":"说;讲","sentence":"Can you speak English?","translation":"你会说英语吗？"},
{"word":"a little","phonetic":"/? ?l?tl/","pos":"phrase","meaning":"一点点","sentence":"I speak a little Spanish.","translation":"我会说一点西班牙语。"},
{"word":"America","phonetic":"/??mer?k?/","pos":"n.","meaning":"美国","sentence":"He lives in America.","translation":"他住在美国。"},
{"word":"sea","phonetic":"/si?/","pos":"n.","meaning":"海","sentence":"The sea is blue.","translation":"大海是蓝色的。"},
{"word":"please","phonetic":"/pli?z/","pos":"int.","meaning":"请","sentence":"Sit down, please.","translation":"请坐。"},
{"word":"bye","phonetic":"/ba?/","pos":"int.","meaning":"再见","sentence":"Bye! See you tomorrow.","translation":"再见！明天见。"},
{"word":"salad","phonetic":"/?s?l?d/","pos":"n.","meaning":"沙拉","sentence":"I ordered a fruit salad.","translation":"我点了一份水果沙拉。"},
{"word":"pork","phonetic":"/p??rk/","pos":"n.","meaning":"猪肉","sentence":"This dish is made of pork.","translation":"这道菜是用猪肉做的。"},
{"word":"sandwich","phonetic":"/?s?nw?t?/","pos":"n.","meaning":"三明治","sentence":"I had a sandwich for lunch.","translation":"我午餐吃了个三明治。"},
{"word":"would you like","phonetic":"/w?d ju la?k/","pos":"phrase","meaning":"你想要...吗","sentence":"Would you like some coffee?","translation":"你想来点咖啡吗？"},
{"word":"I'd like","phonetic":"/a?d la?k/","pos":"phrase","meaning":"我想要","sentence":"I'd like a cup of tea.","translation":"我想要一杯茶。"},
{"word":"afternoon","phonetic":"/??ft?r?nu?n/","pos":"n.","meaning":"下午","sentence":"Good afternoon.","translation":"下午好。"},
{"word":"pay","phonetic":"/pe?/","pos":"v.","meaning":"支付","sentence":"I will pay for the meal.","translation":"我会付饭钱。"},
{"word":"chair","phonetic":"/t?er/","pos":"n.","meaning":"椅子","sentence":"Please sit on the chair.","translation":"请坐在椅子上。"},
{"word":"cheese","phonetic":"/t?i?z/","pos":"n.","meaning":"奶酪","sentence":"I like cheese on my pizza.","translation":"我喜欢披萨上放奶酪。"},
{"word":"chicken","phonetic":"/?t??k?n/","pos":"n.","meaning":"鸡肉;鸡","sentence":"We are having fried chicken.","translation":"我们正在吃炸鸡。"},
{"word":"cup","phonetic":"/k?p/","pos":"n.","meaning":"杯子","sentence":"Would you like a cup of tea?","translation":"你想来杯茶吗？"},
{"word":"have","phonetic":"/h?v/","pos":"v.","meaning":"有;吃","sentence":"I have a car.","translation":"我有一辆车。"},
{"word":"day","phonetic":"/de?/","pos":"n.","meaning":"天;白天","sentence":"It is a sunny day.","translation":"今天是个晴天。"},
{"word":"mall","phonetic":"/m??l/","pos":"n.","meaning":"购物中心","sentence":"Let's go to the mall.","translation":"我们去购物中心吧。"},
{"word":"taxi","phonetic":"/?t?ksi/","pos":"n.","meaning":"出租车","sentence":"I took a taxi home.","translation":"我打车回家的。"},
{"word":"driver","phonetic":"/?dra?v?r/","pos":"n.","meaning":"司机","sentence":"The bus driver is friendly.","translation":"公交车司机很友好。"},
{"word":"friend","phonetic":"/frend/","pos":"n.","meaning":"朋友","sentence":"She is my best friend.","translation":"她是我最好的朋友。"},
{"word":"lock","phonetic":"/lɑ?k/","pos":"v., n.","meaning":"锁上;锁","sentence":"Don't forget to lock the door.","translation":"别忘了锁门。"},
{"word":"doctor","phonetic":"/?dɑ?kt?r/","pos":"n.","meaning":"医生","sentence":"You should see a doctor.","translation":"你应该去看医生。"},
{"word":"bath","phonetic":"/b?θ/","pos":"n.","meaning":"洗澡;浴缸","sentence":"I take a bath every evening.","translation":"我每天晚上洗澡。"},
{"word":"math","phonetic":"/m?θ/","pos":"n.","meaning":"数学","sentence":"Math is my favorite subject.","translation":"数学是我最喜欢的科目。"},
{"word":"game","phonetic":"/ge?m/","pos":"n.","meaning":"游戏;比赛","sentence":"Let's play a game.","translation":"我们玩个游戏吧。"},
{"word":"boring","phonetic":"/?b??r??/","pos":"adj.","meaning":"无聊的","sentence":"The movie was boring.","translation":"那部电影很无聊。"},
{"word":"shirt","phonetic":"/???rt/","pos":"n.","meaning":"衬衫","sentence":"He is wearing a blue shirt.","translation":"他穿着一件蓝衬衫。"},
{"word":"welcome","phonetic":"/?welk?m/","pos":"int., adj., v.","meaning":"欢迎","sentence":"Welcome to our home.","translation":"欢迎来我家。"},
{"word":"need","phonetic":"/ni?d/","pos":"v., n.","meaning":"需要","sentence":"I need your help.","translation":"我需要你的帮助。"},
{"word":"jacket","phonetic":"/?d??k?t/","pos":"n.","meaning":"夹克","sentence":"It's cold, wear a jacket.","translation":"天冷，穿件夹克。"},
{"word":"expensive","phonetic":"/?k?spens?v/","pos":"adj.","meaning":"昂贵的","sentence":"This car is very expensive.","translation":"这辆车很贵。"},
{"word":"cap","phonetic":"/k?p/","pos":"n.","meaning":"鸭舌帽;盖子","sentence":"He is wearing a baseball cap.","translation":"他戴着一顶棒球帽。"},
{"word":"sat","phonetic":"/s?t/","pos":"v.","meaning":"坐(sit的过去式)","sentence":"He sat on the bench.","translation":"他坐在长椅上。"},
{"word":"dollar","phonetic":"/?dɑ?l?r/","pos":"n.","meaning":"美元","sentence":"It costs five dollars.","translation":"它值五美元。"},
{"word":"much","phonetic":"/m?t?/","pos":"adv., adj., pron.","meaning":"许多","sentence":"Thank you very much.","translation":"非常感谢。"},
{"word":"one","phonetic":"/w?n/","pos":"num.","meaning":"一","sentence":"I have one brother.","translation":"我有一个哥哥。"},
{"word":"two","phonetic":"/tu?/","pos":"num.","meaning":"二","sentence":"Two tickets, please.","translation":"请给我两张票。"},
{"word":"three","phonetic":"/θri?/","pos":"num.","meaning":"三","sentence":"I have three cats.","translation":"我有三只猫。"},
{"word":"four","phonetic":"/f??r/","pos":"num.","meaning":"四","sentence":"There are four seasons.","translation":"一年有四季。"},
{"word":"five","phonetic":"/fa?v/","pos":"num.","meaning":"五","sentence":"It is five o'clock.","translation":"现在是五点钟。"},
{"word":"six","phonetic":"/s?ks/","pos":"num.","meaning":"六","sentence":"He is six years old.","translation":"他六岁了。"},
{"word":"seven","phonetic":"/?sev?n/","pos":"num.","meaning":"七","sentence":"There are seven days in a week.","translation":"一周有七天。"},
{"word":"eight","phonetic":"/e?t/","pos":"num.","meaning":"八","sentence":"I wake up at eight.","translation":"我八点醒。"},
{"word":"nine","phonetic":"/na?n/","pos":"num.","meaning":"九","sentence":"Nine comes after eight.","translation":"八之后是九。"},
{"word":"ten","phonetic":"/ten/","pos":"num.","meaning":"十","sentence":"I have ten fingers.","translation":"我有十个手指。"},
{"word":"one hundred","phonetic":"/w?n ?h?ndr?d/","pos":"num.","meaning":"一百","sentence":"It costs one hundred dollars.","translation":"它要一百美元。"},
{"word":"how","phonetic":"/ha?/","pos":"adv.","meaning":"如何;怎样","sentence":"How are you?","translation":"你好吗？"},
{"word":"her","phonetic":"/h??r/","pos":"pron.","meaning":"她的;她(宾格)","sentence":"This is her bag.","translation":"这是她的包。"},
{"word":"sister","phonetic":"/?s?st?r/","pos":"n.","meaning":"姐妹","sentence":"My sister is older than me.","translation":"我姐姐比我大。"},
{"word":"boyfriend","phonetic":"/?b??frend/","pos":"n.","meaning":"男朋友","sentence":"She has a new boyfriend.","translation":"她交了新男朋友。"},
{"word":"brother","phonetic":"/?br?e?r/","pos":"n.","meaning":"兄弟","sentence":"I play games with my brother.","translation":"我和我弟弟玩游戏。"},
{"word":"girlfriend","phonetic":"/?g??rlfrend/","pos":"n.","meaning":"女朋友","sentence":"His girlfriend is very nice.","translation":"他女朋友很友善。"},
{"word":"his","phonetic":"/h?z/","pos":"pron.","meaning":"他的","sentence":"His name is Tom.","translation":"他的名字叫汤姆。"},
{"word":"husband","phonetic":"/?h?zb?nd/","pos":"n.","meaning":"丈夫","sentence":"Her husband is a cook.","translation":"她丈夫是个厨师。"},
{"word":"wife","phonetic":"/wa?f/","pos":"n.","meaning":"妻子","sentence":"He loves his wife very much.","translation":"他非常爱他的妻子。"},
{"word":"tall","phonetic":"/t??l/","pos":"adj.","meaning":"高的","sentence":"He is very tall.","translation":"他很高。"},
{"word":"rich","phonetic":"/r?t?/","pos":"adj.","meaning":"富有的","sentence":"He wants to be rich.","translation":"他想变富有。"},
{"word":"life","phonetic":"/la?f/","pos":"n.","meaning":"生活;生命","sentence":"City life is busy.","translation":"城市生活很忙碌。"},
{"word":"smart","phonetic":"/smɑ?rt/","pos":"adj.","meaning":"聪明的","sentence":"She is a smart student.","translation":"她是个聪明的学生。"},
{"word":"son","phonetic":"/s?n/","pos":"n.","meaning":"儿子","sentence":"His son goes to school.","translation":"他儿子去上学。"},
{"word":"dear","phonetic":"/d?r/","pos":"adj.","meaning":"亲爱的;昂贵的","sentence":"Dear friend, how are you?","translation":"亲爱的朋友，你好吗？"},
{"word":"years old","phonetic":"/j?rz o?ld/","pos":"phrase","meaning":"岁","sentence":"I am twenty years old.","translation":"我二十岁。"},
{"word":"daughter","phonetic":"/?d??t?r/","pos":"n.","meaning":"女儿","sentence":"Their daughter is cute.","translation":"他们的女儿很可爱。"},
{"word":"beer","phonetic":"/b?r/","pos":"n.","meaning":"啤酒","sentence":"He likes to drink beer.","translation":"他喜欢喝啤酒。"},
{"word":"pizza","phonetic":"/?pi?ts?/","pos":"n.","meaning":"披萨","sentence":"We ordered a pizza.","translation":"我们点了披萨。"},
{"word":"of","phonetic":"/?v/","pos":"prep.","meaning":"...的","sentence":"A cup of tea.","translation":"一杯茶。"},
{"word":"cheers","phonetic":"/t??rz/","pos":"int.","meaning":"干杯","sentence":"Cheers to our friendship!","translation":"为我们的友谊干杯！"},
{"word":"goodbye","phonetic":"/?g?d?ba?/","pos":"int.","meaning":"再见","sentence":"Goodbye, see you soon.","translation":"再见，回头见。"},
{"word":"with","phonetic":"/w?e/","pos":"prep.","meaning":"和...一起","sentence":"Come with me.","translation":"跟我来。"},
{"word":"milk","phonetic":"/m?lk/","pos":"n.","meaning":"牛奶","sentence":"I drink milk for breakfast.","translation":"我早餐喝牛奶。"},
{"word":"sugar","phonetic":"/???g?r/","pos":"n.","meaning":"糖","sentence":"Do you take sugar in your coffee?","translation":"你咖啡里加糖吗？"},
{"word":"restaurant","phonetic":"/?rest?rɑ?nt/","pos":"n.","meaning":"餐厅","sentence":"This is a good restaurant.","translation":"这是一家好餐厅。"},
{"word":"table","phonetic":"/?te?bl/","pos":"n.","meaning":"桌子","sentence":"The food is on the table.","translation":"食物在桌子上。"},
{"word":"check","phonetic":"/t?ek/","pos":"v., n.","meaning":"检查;买单","sentence":"Check, please.","translation":"买单，谢谢。"},
{"word":"menu","phonetic":"/?menju?/","pos":"n.","meaning":"菜单","sentence":"Can I have the menu?","translation":"能给我菜单吗？"},
{"word":"for","phonetic":"/f??r/","pos":"prep.","meaning":"为了;给","sentence":"This gift is for you.","translation":"这份礼物是给你的。"},
{"word":"important","phonetic":"/?m?p??rtnt/","pos":"adj.","meaning":"重要的","sentence":"This is an important meeting.","translation":"这是一个重要的会议。"},
{"word":"cool","phonetic":"/ku?l/","pos":"adj.","meaning":"凉爽的;酷的","sentence":"The weather is cool.","translation":"天气很凉爽。"},
{"word":"exact","phonetic":"/?g?z?kt/","pos":"adj.","meaning":"确切的","sentence":"What is the exact time?","translation":"确切时间是多少？"},
{"word":"question","phonetic":"/?kwest??n/","pos":"n.","meaning":"问题","sentence":"I have a question.","translation":"我有个问题。"},
{"word":"many","phonetic":"/?meni/","pos":"adj., pron.","meaning":"许多","sentence":"Many people like music.","translation":"许多人喜欢音乐。"},
{"word":"school","phonetic":"/sku?l/","pos":"n.","meaning":"学校","sentence":"I walk to school.","translation":"我走路去上学。"},
{"word":"pass","phonetic":"/p?s/","pos":"v.","meaning":"通过;传递","sentence":"Did you pass the exam?","translation":"你通过考试了吗？"},
{"word":"class","phonetic":"/kl?s/","pos":"n.","meaning":"班级;课","sentence":"The class starts at nine.","translation":"九点开始上课。"},
{"word":"glass","phonetic":"/gl?s/","pos":"n.","meaning":"玻璃;玻璃杯","sentence":"Be careful with the glass.","translation":"小心那个玻璃杯。"},
{"word":"difficult","phonetic":"/?d?f?k?lt/","pos":"adj.","meaning":"困难的","sentence":"The test was difficult.","translation":"考试很难。"},
{"word":"has","phonetic":"/h?z/","pos":"v.","meaning":"有(have的第三人称单数)","sentence":"He has a dog.","translation":"他有一只狗。"},
{"word":"exam","phonetic":"/?g?z?m/","pos":"n.","meaning":"考试","sentence":"I have an exam tomorrow.","translation":"我明天有个考试。"},
{"word":"easy","phonetic":"/?i?zi/","pos":"adj.","meaning":"容易的","sentence":"This game is easy.","translation":"这个游戏很容易。"},
{"word":"today","phonetic":"/t??de?/","pos":"n., adv.","meaning":"今天","sentence":"How are you today?","translation":"你今天怎么样？"},
{"word":"an","phonetic":"/?n/","pos":"art.","meaning":"一个","sentence":"I ate an apple.","translation":"我吃了一个苹果。"},
{"word":"these","phonetic":"/ei?z/","pos":"pron., adj.","meaning":"这些","sentence":"These are my shoes.","translation":"这些是我的鞋。"},
{"word":"favorite","phonetic":"/?fe?v?r?t/","pos":"adj., n.","meaning":"最喜欢的","sentence":"Blue is my favorite color.","translation":"蓝色是我最喜欢的颜色。"},
{"word":"color","phonetic":"/?k?l?r/","pos":"n.","meaning":"颜色","sentence":"What color do you like?","translation":"你喜欢什么颜色？"},
{"word":"beautiful","phonetic":"/?bju?t?fl/","pos":"adj.","meaning":"美丽的","sentence":"The flowers are beautiful.","translation":"这些花很美。"},
{"word":"orange","phonetic":"/???r?nd?/","pos":"n., adj.","meaning":"橙子;橙色的","sentence":"I like orange juice.","translation":"我喜欢橙汁。"},
{"word":"dress","phonetic":"/dres/","pos":"n., v.","meaning":"连衣裙;穿衣","sentence":"She is wearing a red dress.","translation":"她穿着一件红色的连衣裙。"},
{"word":"too","phonetic":"/tu?/","pos":"adv.","meaning":"也;太","sentence":"I like it too.","translation":"我也喜欢。"},
{"word":"really","phonetic":"/?ri??li/","pos":"adv.","meaning":"真正地","sentence":"I really like this song.","translation":"我真的很喜欢这首歌。"},
{"word":"song","phonetic":"/s???/","pos":"n.","meaning":"歌曲","sentence":"Sing a song for us.","translation":"给我们唱首歌吧。"},
{"word":"pants","phonetic":"/p?nts/","pos":"n.","meaning":"裤子","sentence":"My pants are too long.","translation":"我的裤子太长了。"},
{"word":"shoe","phonetic":"/?u?/","pos":"n.","meaning":"鞋","sentence":"I lost one shoe.","translation":"我丢了一只鞋。"},
{"word":"key","phonetic":"/ki?/","pos":"n.","meaning":"钥匙;关键","sentence":"Where is my car key?","translation":"我的车钥匙在哪？"},
{"word":"bar","phonetic":"/bɑ?r/","pos":"n.","meaning":"酒吧;条","sentence":"They met at a bar.","translation":"他们在酒吧见的面。"},
{"word":"that's","phonetic":"/e?ts/","pos":"abbr.","meaning":"那是(that is)","sentence":"That's a good idea.","translation":"那是个好主意。"},
{"word":"you're welcome","phonetic":"/j?r ?welk?m/","pos":"phrase","meaning":"不客气","sentence":"'Thank you.' 'You're welcome.'","translation":"“谢谢。”“不客气。”"},
{"word":"car","phonetic":"/kɑ?r/","pos":"n.","meaning":"汽车","sentence":"He drives a nice car.","translation":"他开着一辆好车。"},
{"word":"except","phonetic":"/?k?sept/","pos":"prep.","meaning":"除了...之外","sentence":"Everyone is here except Tom.","translation":"除了汤姆，大家都在这。"},
{"word":"very","phonetic":"/?veri/","pos":"adv.","meaning":"非常","sentence":"It is very hot today.","translation":"今天非常热。"},
{"word":"parent","phonetic":"/?per?nt/","pos":"n.","meaning":"父母","sentence":"I live with my parents.","translation":"我和父母住在一起。"},
{"word":"friendly","phonetic":"/?frendli/","pos":"adj.","meaning":"友好的","sentence":"The people here are friendly.","translation":"这里的人很友好。"},
{"word":"person","phonetic":"/?p??rsn/","pos":"n.","meaning":"人","sentence":"She is a nice person.","translation":"她是个好人。"},
{"word":"where","phonetic":"/wer/","pos":"adv.","meaning":"在哪里","sentence":"Where are you going?","translation":"你去哪里？"},
{"word":"here","phonetic":"/h?r/","pos":"adv.","meaning":"这里","sentence":"Come here.","translation":"来这里。"},
{"word":"best","phonetic":"/best/","pos":"adj., adv.","meaning":"最好的","sentence":"He is my best friend.","translation":"他是我最好的朋友。"},
{"word":"happy","phonetic":"/?h?pi/","pos":"adj.","meaning":"快乐的","sentence":"I am very happy today.","translation":"我今天很快乐。"},
{"word":"family","phonetic":"/?f?m?li/","pos":"n.","meaning":"家庭;家人","sentence":"I love my family.","translation":"我爱我的家人。"},
{"word":"always","phonetic":"/???lwe?z/","pos":"adv.","meaning":"总是","sentence":"He is always late.","translation":"他总是迟到。"},
{"word":"busy","phonetic":"/?b?zi/","pos":"adj.","meaning":"忙碌的","sentence":"I am busy working.","translation":"我忙着工作。"},
{"word":"love","phonetic":"/l?v/","pos":"v., n.","meaning":"爱","sentence":"I love music.","translation":"我爱音乐。"},
{"word":"that","phonetic":"/e?t/","pos":"pron., adj.","meaning":"那个","sentence":"What is that?","translation":"那是什么？"},
{"word":"funny","phonetic":"/?f?ni/","pos":"adj.","meaning":"有趣的;滑稽的","sentence":"The movie is very funny.","translation":"这部电影很滑稽。"},
{"word":"sunny","phonetic":"/?s?ni/","pos":"adj.","meaning":"晴朗的","sentence":"It is a sunny day.","translation":"今天是个晴天。"},
{"word":"bad","phonetic":"/b?d/","pos":"adj.","meaning":"坏的;糟糕的","sentence":"Smoking is bad for health.","translation":"吸烟对健康有害。"},
{"word":"do","phonetic":"/du?/","pos":"v.","meaning":"做","sentence":"What do you do?","translation":"你是做什么工作的？"},
{"word":"country","phonetic":"/?k?ntri/","pos":"n.","meaning":"国家;乡村","sentence":"Which country are you from?","translation":"你来自哪个国家？"},
{"word":"Japan","phonetic":"/d???p?n/","pos":"n.","meaning":"日本","sentence":"Tokyo is in Japan.","translation":"东京在日本。"},
{"word":"live in","phonetic":"/l?v ?n/","pos":"phrase","meaning":"居住在","sentence":"I live in New York.","translation":"我住在纽约。"},
{"word":"language","phonetic":"/?l??gw?d?/","pos":"n.","meaning":"语言","sentence":"English is a global language.","translation":"英语是一门全球语言。"},
{"word":"don't","phonetic":"/do?nt/","pos":"abbr.","meaning":"不(do not)","sentence":"I don't know.","translation":"我不知道。"},
{"word":"but","phonetic":"/b?t/","pos":"conj.","meaning":"但是","sentence":"I'm tired but happy.","translation":"我很累但很开心。"},
{"word":"Spanish","phonetic":"/?sp?n??/","pos":"n., adj.","meaning":"西班牙语;西班牙的","sentence":"She speaks Spanish.","translation":"她说西班牙语。"},
{"word":"cut","phonetic":"/k?t/","pos":"v.","meaning":"切;剪","sentence":"Cut the cake, please.","translation":"请切蛋糕。"},
{"word":"know","phonetic":"/no?/","pos":"v.","meaning":"知道;认识","sentence":"I know the answer.","translation":"我知道答案。"},
{"word":"address","phonetic":"/??dres/","pos":"n.","meaning":"地址","sentence":"What is your address?","translation":"你的地址是什么？"},
{"word":"no problem","phonetic":"/no? ?prɑ?bl?m/","pos":"phrase","meaning":"没问题","sentence":"'Can you help me?' 'No problem.'","translation":"“你能帮我吗？”“没问题。”"},
{"word":"sorry","phonetic":"/?sɑ?ri/","pos":"adj., int.","meaning":"对不起;抱歉的","sentence":"I am sorry for being late.","translation":"对不起我迟到了。"},
{"word":"pet","phonetic":"/pet/","pos":"n.","meaning":"宠物","sentence":"Do you have a pet?","translation":"你有宠物吗？"},
{"word":"name","phonetic":"/ne?m/","pos":"n.","meaning":"名字","sentence":"My name is John.","translation":"我叫约翰。"},
{"word":"understand","phonetic":"/??nd?r?st?nd/","pos":"v.","meaning":"理解","sentence":"I understand what you mean.","translation":"我明白你的意思。"},
{"word":"email","phonetic":"/?i?me?l/","pos":"n., v.","meaning":"电子邮件","sentence":"Send me an email.","translation":"给我发个邮件。"},
{"word":"hospital","phonetic":"/?hɑ?sp?tl/","pos":"n.","meaning":"医院","sentence":"He works in a hospital.","translation":"他在医院工作。"},
{"word":"stand","phonetic":"/st?nd/","pos":"v.","meaning":"站立;忍受","sentence":"Please stand up.","translation":"请起立。"},
{"word":"work","phonetic":"/w??rk/","pos":"v., n.","meaning":"工作","sentence":"I work at a bank.","translation":"我在银行工作。"},
{"word":"together","phonetic":"/t??gee?r/","pos":"adv.","meaning":"一起","sentence":"Let's go together.","translation":"我们一起去吧。"},
{"word":"what do you do","phonetic":"/wɑ?t du ju du?/","pos":"phrase","meaning":"你是做什么的","sentence":"What do you do for a living?","translation":"你是靠什么谋生的？"},
{"word":"office","phonetic":"/???f?s/","pos":"n.","meaning":"办公室","sentence":"My office is on the second floor.","translation":"我的办公室在二楼。"},
{"word":"meeting","phonetic":"/?mi?t??/","pos":"n.","meaning":"会议","sentence":"We have a meeting at ten.","translation":"我们十点有个会。"},
{"word":"bank","phonetic":"/b??k/","pos":"n.","meaning":"银行","sentence":"I need to go to the bank.","translation":"我得去趟银行。"},
{"word":"job","phonetic":"/d?ɑ?b/","pos":"n.","meaning":"工作","sentence":"I love my job.","translation":"我爱我的工作。"},
{"word":"lot","phonetic":"/lɑ?t/","pos":"n.","meaning":"大量","sentence":"Thanks a lot.","translation":"多谢。"},
{"word":"beach","phonetic":"/bi?t?/","pos":"n.","meaning":"海滩","sentence":"We walked on the beach.","translation":"我们在海滩上散步。"},
{"word":"tonight","phonetic":"/t??na?t/","pos":"adv., n.","meaning":"今晚","sentence":"Are you free tonight?","translation":"你今晚有空吗？"},
{"word":"study","phonetic":"/?st?di/","pos":"v., n.","meaning":"学习","sentence":"I study English every day.","translation":"我每天学英语。"},
{"word":"teach","phonetic":"/ti?t?/","pos":"v.","meaning":"教","sentence":"She teaches math.","translation":"她教数学。"},
{"word":"university","phonetic":"/?ju?n??v??rs?ti/","pos":"n.","meaning":"大学","sentence":"He is a university student.","translation":"他是一名大学生。"},
{"word":"on","phonetic":"/ɑ?n/","pos":"prep.","meaning":"在...上;关于","sentence":"The book is on the desk.","translation":"书在桌子上。"},
{"word":"Sunday","phonetic":"/?s?nde?/","pos":"n.","meaning":"星期日","sentence":"I relax on Sunday.","translation":"我周日休息。"},
{"word":"Saturday","phonetic":"/?s?t?rde?/","pos":"n.","meaning":"星期六","sentence":"We go shopping on Saturday.","translation":"我们周六去购物。"},
{"word":"Friday","phonetic":"/?fra?de?/","pos":"n.","meaning":"星期五","sentence":"Thank God it's Friday.","translation":"谢天谢地今天是周五。"},
{"word":"Thursday","phonetic":"/?θ??rzde?/","pos":"n.","meaning":"星期四","sentence":"We have a meeting on Thursday.","translation":"我们周四有个会。"},
{"word":"Wednesday","phonetic":"/?wenzde?/","pos":"n.","meaning":"星期三","sentence":"Today is Wednesday.","translation":"今天是星期三。"},
{"word":"Tuesday","phonetic":"/?tu?zde?/","pos":"n.","meaning":"星期二","sentence":"See you on Tuesday.","translation":"周二见。"},
{"word":"Monday","phonetic":"/?m?nde?/","pos":"n.","meaning":"星期一","sentence":"Work starts on Monday.","translation":"周一开始工作。"},
{"word":"sun","phonetic":"/s?n/","pos":"n.","meaning":"太阳","sentence":"The sun is shining.","translation":"阳光普照。"},
{"word":"in","phonetic":"/?n/","pos":"prep.","meaning":"在...里面","sentence":"The cat is in the box.","translation":"猫在盒子里。"},
{"word":"city","phonetic":"/?s?ti/","pos":"n.","meaning":"城市","sentence":"I love living in the city.","translation":"我喜欢住在城市里。"},
{"word":"use","phonetic":"/ju?z/","pos":"v.","meaning":"使用","sentence":"Can I use your pen?","translation":"我能用你的笔吗？"},
{"word":"apple","phonetic":"/??pl/","pos":"n.","meaning":"苹果","sentence":"An apple a day keeps the doctor away.","translation":"一天一苹果，医生远离我。"},
{"word":"every day","phonetic":"/?evri de?/","pos":"phrase","meaning":"每天","sentence":"I exercise every day.","translation":"我每天锻炼。"},
{"word":"breakfast","phonetic":"/?brekf?st/","pos":"n.","meaning":"早餐","sentence":"I eat eggs for breakfast.","translation":"我早餐吃鸡蛋。"},
{"word":"link","phonetic":"/l??k/","pos":"n., v.","meaning":"链接;连接","sentence":"Click the link below.","translation":"点击下方的链接。"},
{"word":"eat","phonetic":"/i?t/","pos":"v.","meaning":"吃","sentence":"Let's eat dinner.","translation":"我们要吃晚饭了。"},
{"word":"rice","phonetic":"/ra?s/","pos":"n.","meaning":"米饭","sentence":"I like to eat rice.","translation":"我喜欢吃米饭。"},
{"word":"some","phonetic":"/s?m/","pos":"det., pron.","meaning":"一些","sentence":"I need some water.","translation":"我需要一些水。"},
{"word":"want","phonetic":"/wɑ?nt/","pos":"v.","meaning":"想要","sentence":"I want to go home.","translation":"我想回家。"},
{"word":"bread","phonetic":"/bred/","pos":"n.","meaning":"面包","sentence":"Fresh bread smells good.","translation":"新鲜面包闻起来很香。"},
{"word":"noodles","phonetic":"/?nu?dlz/","pos":"n.","meaning":"面条","sentence":"I love beef noodles.","translation":"我喜欢牛肉面。"},
{"word":"mice","phonetic":"/ma?s/","pos":"n.","meaning":"老鼠(mouse的复数)","sentence":"Cats catch mice.","translation":"猫抓老鼠。"},
{"word":"egg","phonetic":"/eg/","pos":"n.","meaning":"鸡蛋","sentence":"I boiled an egg.","translation":"我煮了个鸡蛋。"},
{"word":"never","phonetic":"/?nev?r/","pos":"adv.","meaning":"从不","sentence":"I never smoke.","translation":"我从不吸烟。"},
{"word":"vegetable","phonetic":"/?ved?t?bl/","pos":"n.","meaning":"蔬菜","sentence":"Eat more vegetables.","translation":"多吃蔬菜。"},
{"word":"fruit","phonetic":"/fru?t/","pos":"n.","meaning":"水果","sentence":"Fresh fruit is healthy.","translation":"新鲜水果很健康。"},
{"word":"soup","phonetic":"/su?p/","pos":"n.","meaning":"汤","sentence":"The soup is hot.","translation":"汤很热。"},
{"word":"tomato","phonetic":"/t??me?to?/","pos":"n.","meaning":"西红柿","sentence":"I like tomato soup.","translation":"我喜欢番茄汤。"},
{"word":"potato","phonetic":"/p??te?to?/","pos":"n.","meaning":"土豆","sentence":"I like baked potatoes.","translation":"我喜欢烤土豆。"},
{"word":"seeds","phonetic":"/si?dz/","pos":"n.","meaning":"种子","sentence":"Plant the seeds in the soil.","translation":"把种子种在土里。"},
{"word":"read","phonetic":"/ri?d/","pos":"v.","meaning":"阅读","sentence":"I read a book every week.","translation":"我每周读一本书。"},
{"word":"play","phonetic":"/ple?/","pos":"v.","meaning":"玩;播放","sentence":"They play soccer.","translation":"他们踢足球。"},
{"word":"leader","phonetic":"/?li?d?r/","pos":"n.","meaning":"领导者","sentence":"He is a good leader.","translation":"他是个好领导。"},
{"word":"basketball","phonetic":"/?b?sk?tb??l/","pos":"n.","meaning":"篮球","sentence":"I play basketball.","translation":"我打篮球。"},
{"word":"tennis","phonetic":"/?ten?s/","pos":"n.","meaning":"网球","sentence":"Do you play tennis?","translation":"你打网球吗？"},
{"word":"baseball","phonetic":"/?be?sb??l/","pos":"n.","meaning":"棒球","sentence":"Baseball is popular in America.","translation":"棒球在美国很受欢迎。"},
{"word":"does","phonetic":"/d?z/","pos":"v.","meaning":"做(do的第三人称单数)","sentence":"He does his homework.","translation":"他做他的作业。"},
{"word":"every","phonetic":"/?evri/","pos":"det.","meaning":"每一个","sentence":"Every student has a book.","translation":"每个学生都有一本书。"},
{"word":"noodle","phonetic":"/?nu?dl/","pos":"n.","meaning":"面条","sentence":"This is a long noodle.","translation":"这是一根长面条。"},
{"word":"movie","phonetic":"/?mu?vi/","pos":"n.","meaning":"电影","sentence":"Let's watch a movie.","translation":"我们看电影吧。"},
{"word":"draw","phonetic":"/dr??/","pos":"v.","meaning":"画","sentence":"She likes to draw pictures.","translation":"她喜欢画画。"},
{"word":"sing","phonetic":"/s??/","pos":"v.","meaning":"唱歌","sentence":"He sings very well.","translation":"他唱得很好。"},
{"word":"music","phonetic":"/?mju?z?k/","pos":"n.","meaning":"音乐","sentence":"I listen to music.","translation":"我听音乐。"},
{"word":"cook","phonetic":"/k?k/","pos":"v., n.","meaning":"烹饪;厨师","sentence":"I like to cook dinner.","translation":"我喜欢做晚饭。"},
{"word":"doesn't","phonetic":"/?d?znt/","pos":"abbr.","meaning":"不(does not)","sentence":"He doesn't like spicy food.","translation":"他不喜欢吃辣。"},
{"word":"sometimes","phonetic":"/?s?mta?mz/","pos":"adv.","meaning":"有时","sentence":"I sometimes walk to work.","translation":"我有时走路去上班。"},
{"word":"time","phonetic":"/ta?m/","pos":"n.","meaning":"时间;次数","sentence":"What time is it?","translation":"几点了？"},
{"word":"fine","phonetic":"/fa?n/","pos":"adj.","meaning":"好的;健康的","sentence":"I am fine, thank you.","translation":"我很好，谢谢。"},
{"word":"usually","phonetic":"/?ju??u?li/","pos":"adv.","meaning":"通常","sentence":"I usually wake up at 7.","translation":"我通常7点醒。"},
{"word":"train","phonetic":"/tre?n/","pos":"n., v.","meaning":"火车;训练","sentence":"The train is late.","translation":"火车晚点了。"},
{"word":"airport","phonetic":"/?erp??rt/","pos":"n.","meaning":"机场","sentence":"I am going to the airport.","translation":"我要去机场。"},
{"word":"station","phonetic":"/?ste??n/","pos":"n.","meaning":"车站","sentence":"Meet me at the station.","translation":"在车站见我。"},
{"word":"the","phonetic":"/e?/","pos":"art.","meaning":"这;那","sentence":"The book is red.","translation":"那本书是红色的。"},
{"word":"subway","phonetic":"/?s?bwe?/","pos":"n.","meaning":"地铁","sentence":"I take the subway to school.","translation":"我坐地铁去学校。"},
{"word":"bathroom","phonetic":"/?b?θru?m/","pos":"n.","meaning":"浴室;洗手间","sentence":"The bathroom is clean.","translation":"浴室很干净。"},
{"word":"over there","phonetic":"/?o?v?r eer/","pos":"phrase","meaning":"在那边","sentence":"The shop is over there.","translation":"商店在那边。"},
{"word":"where is","phonetic":"/wer ?z/","pos":"phrase","meaning":"...在哪里","sentence":"Where is the library?","translation":"图书馆在哪里？"},
{"word":"over","phonetic":"/?o?v?r/","pos":"prep., adv.","meaning":"结束;在...上方","sentence":"The game is over.","translation":"比赛结束了。"},
{"word":"plane","phonetic":"/ple?n/","pos":"n.","meaning":"飞机","sentence":"The plane is flying high.","translation":"飞机飞得很高。"},
{"word":"ticket","phonetic":"/?t?k?t/","pos":"n.","meaning":"票","sentence":"I bought a movie ticket.","translation":"我买了张电影票。"},
{"word":"right","phonetic":"/ra?t/","pos":"adj., n.","meaning":"正确的;右边","sentence":"Turn right at the corner.","translation":"在拐角处右转。"},
{"word":"passport","phonetic":"/?p?sp??rt/","pos":"n.","meaning":"护照","sentence":"Show me your passport.","translation":"请出示护照。"},
{"word":"bus","phonetic":"/b?s/","pos":"n.","meaning":"公共汽车","sentence":"The bus is coming.","translation":"公交车来了。"},
{"word":"hotel","phonetic":"/ho??tel/","pos":"n.","meaning":"酒店","sentence":"We stayed at a hotel.","translation":"我们住在一家酒店。"},
{"word":"ticket office","phonetic":"/?t?k?t ??f?s/","pos":"n.","meaning":"售票处","sentence":"The ticket office is closed.","translation":"售票处关门了。"},
{"word":"port","phonetic":"/p??rt/","pos":"n.","meaning":"港口","sentence":"The ship is in the port.","translation":"船在港口。"},
{"word":"late","phonetic":"/le?t/","pos":"adj.","meaning":"迟的;晚的","sentence":"Sorry I am late.","translation":"对不起我迟到了。"},
{"word":"last","phonetic":"/l?st/","pos":"adj., adv.","meaning":"最后的;上一个","sentence":"Last night was fun.","translation":"昨晚很有趣。"},
{"word":"closed","phonetic":"/klo?zd/","pos":"adj.","meaning":"关闭的","sentence":"The shop is closed.","translation":"商店关门了。"},
{"word":"what is","phonetic":"/wɑ?t ?z/","pos":"phrase","meaning":"...是什么","sentence":"What is your name?","translation":"你叫什么名字？"},
{"word":"guy","phonetic":"/ga?/","pos":"n.","meaning":"家伙;人","sentence":"He is a nice guy.","translation":"他是个好人。"},
{"word":"go shopping","phonetic":"/go? ??ɑ?p??/","pos":"phrase","meaning":"去购物","sentence":"Let's go shopping.","translation":"我们去购物吧。"},
{"word":"want to","phonetic":"/wɑ?nt tu/","pos":"phrase","meaning":"想要","sentence":"I want to sleep.","translation":"我想睡觉。"},
{"word":"skirt","phonetic":"/sk??rt/","pos":"n.","meaning":"裙子","sentence":"She is wearing a pink skirt.","translation":"她穿着一条粉色的裙子。"},
{"word":"jeans","phonetic":"/d?i?nz/","pos":"n.","meaning":"牛仔裤","sentence":"I like blue jeans.","translation":"我喜欢蓝色牛仔裤。"},
{"word":"those","phonetic":"/eo?z/","pos":"pron.","meaning":"那些","sentence":"Those are my books.","translation":"那些是我的书。"},
{"word":"t-shirt","phonetic":"/?ti? ???rt/","pos":"n.","meaning":"T恤","sentence":"He wears a white t-shirt.","translation":"他穿着一件白色T恤。"},
{"word":"different","phonetic":"/?d?fr?nt/","pos":"adj.","meaning":"不同的","sentence":"They have different ideas.","translation":"他们有不同的想法。"},
{"word":"store","phonetic":"/st??r/","pos":"n.","meaning":"商店","sentence":"I am going to the store.","translation":"我要去商店。"},
{"word":"clothes","phonetic":"/klo?ez/","pos":"n.","meaning":"衣服","sentence":"She bought new clothes.","translation":"她买了新衣服。"},
{"word":"clothes store","phonetic":"/klo?ez st??r/","pos":"n.","meaning":"服装店","sentence":"The clothes store is open.","translation":"服装店开门了。"},
{"word":"open","phonetic":"/?o?p?n/","pos":"adj., v.","meaning":"开着的;打开","sentence":"Open the door, please.","translation":"请开门。"},
{"word":"hand","phonetic":"/h?nd/","pos":"n.","meaning":"手","sentence":"Wash your hands.","translation":"洗手。"},
{"word":"live","phonetic":"/l?v/","pos":"v.","meaning":"居住;生活","sentence":"I live in this city.","translation":"我住在这个城市。"},
{"word":"often","phonetic":"/???fn/","pos":"adv.","meaning":"经常","sentence":"I often read books.","translation":"我经常看书。"},
{"word":"wash","phonetic":"/wɑ??/","pos":"v.","meaning":"洗","sentence":"I wash my face.","translation":"我洗脸。"},
{"word":"face","phonetic":"/fe?s/","pos":"n.","meaning":"脸","sentence":"He has a round face.","translation":"他有一张圆脸。"},
{"word":"bed","phonetic":"/bed/","pos":"n.","meaning":"床","sentence":"I go to bed at ten.","translation":"我十点上床睡觉。"},
{"word":"grandma","phonetic":"/?gr?nmɑ?/","pos":"n.","meaning":"奶奶;外婆","sentence":"My grandma loves me.","translation":"我奶奶很爱我。"},
{"word":"grandpa","phonetic":"/?gr?npɑ?/","pos":"n.","meaning":"爷爷;外公","sentence":"My grandpa tells stories.","translation":"我爷爷讲故事。"},
{"word":"watches","phonetic":"/?wɑ?t??z/","pos":"v.","meaning":"观看(watch的第三人称单数)","sentence":"He watches TV.","translation":"他看电视。"},
{"word":"eye","phonetic":"/a?/","pos":"n.","meaning":"眼睛","sentence":"She has blue eyes.","translation":"她有蓝眼睛。"},
{"word":"brown","phonetic":"/bra?n/","pos":"adj., n.","meaning":"棕色的;棕色","sentence":"He has brown hair.","translation":"他有棕色的头发。"},
{"word":"hair","phonetic":"/her/","pos":"n.","meaning":"头发","sentence":"Her hair is long.","translation":"她的头发很长。"},
{"word":"when","phonetic":"/wen/","pos":"adv., conj.","meaning":"什么时候","sentence":"When will you come?","translation":"你什么时候来？"},
{"word":"beef","phonetic":"/bi?f/","pos":"n.","meaning":"牛肉","sentence":"I like to eat beef.","translation":"我喜欢吃牛肉。"},
{"word":"would like to","phonetic":"/w?d la?k tu/","pos":"phrase","meaning":"想要","sentence":"I would like to order now.","translation":"我现在想点餐。"},
{"word":"food","phonetic":"/fu?d/","pos":"n.","meaning":"食物","sentence":"The food is delicious.","translation":"食物很美味。"},
{"word":"make","phonetic":"/me?k/","pos":"v.","meaning":"制作","sentence":"I make breakfast.","translation":"我做早餐。"},
{"word":"dinner","phonetic":"/?d?n?r/","pos":"n.","meaning":"晚餐","sentence":"Dinner is ready.","translation":"晚饭做好了。"},
{"word":"lunch","phonetic":"/l?nt?/","pos":"n.","meaning":"午餐","sentence":"I have a sandwich for lunch.","translation":"我午餐吃三明治。"},
{"word":"yesterday","phonetic":"/?jest?rde?/","pos":"n., adv.","meaning":"昨天","sentence":"I went to the park yesterday.","translation":"我昨天去了公园。"},
{"word":"museum","phonetic":"/mj??zi??m/","pos":"n.","meaning":"博物馆","sentence":"The museum is closed on Mondays.","translation":"博物馆周一闭馆。"},
{"word":"still","phonetic":"/st?l/","pos":"adv., adj.","meaning":"仍然，还；静止的","sentence":"Do you still live in London?","translation":"你还住在伦敦吗？"},
{"word":"delicious","phonetic":"/d??l???s/","pos":"adj.","meaning":"美味的，可口的","sentence":"The dinner was delicious.","translation":"晚餐很美味。"},
{"word":"remember","phonetic":"/r??memb?r/","pos":"v.","meaning":"记得，记起","sentence":"Please remember to call me.","translation":"请记得给我打电话。"},
{"word":"reason","phonetic":"/?ri?zn/","pos":"n.","meaning":"理由，原因","sentence":"There is no reason to worry.","translation":"没有理由担心。"},
{"word":"visit","phonetic":"/?v?z?t/","pos":"v., n.","meaning":"参观，拜访","sentence":"I want to visit China someday.","translation":"我想有一天去中国旅游。"},
{"word":"hit","phonetic":"/h?t/","pos":"v., n.","meaning":"打，击；(演出等)成功","sentence":"The new movie is a big hit.","translation":"这部新电影非常成功。"}


]
