/* 单词数据：从你的原始文件拆分出来 */
window.WORDS = [
  {word:"dog",phonetic:"/dɔɡ/",pos:"n.",meaning:"狗",sentence:"The dog is barking.",translation:"这只狗在叫。"},
  {word:"cat",phonetic:"/kæt/",pos:"n.",meaning:"猫",sentence:"I have a cute cat.",translation:"我有一只可爱的猫。"},
  {word:"you",phonetic:"/juː/",pos:"pron.",meaning:"你，你们",sentence:"Nice to meet you.",translation:"很高兴见到你。"},
  {word:"I",phonetic:"/aɪ/",pos:"pron.",meaning:"我",sentence:"I am a student.",translation:"我是一个学生。"},
  {word:"your",phonetic:"/jɔːr/",pos:"pron.",meaning:"你的，你们的",sentence:"Is this your book?",translation:"这是你的书吗？"},
  {word:"my",phonetic:"/maɪ/",pos:"pron.",meaning:"我的",sentence:"My name is Tom.",translation:"我的名字叫汤姆。"},
  {word:"Chinese",phonetic:"/ˌtʃaɪˈniːz/",pos:"adj., n.",meaning:"中国的，中文",sentence:"She speaks Chinese well.",translation:"她中文说得很好。"},
  {word:"English",phonetic:"/ˈɪŋɡlɪʃ/",pos:"adj., n.",meaning:"英语，英国的",sentence:"I represent the English class.",translation:"我代表英语班。"},
  {word:"teacher",phonetic:"/ˈtiːtʃər/",pos:"n.",meaning:"老师",sentence:"He is a math teacher.",translation:"他是一位数学老师。"},
  {word:"mother",phonetic:"/ˈmʌðər/",pos:"n.",meaning:"母亲",sentence:"My mother is cooking.",translation:"我妈妈正在做饭。"},
  {word:"father",phonetic:"/ˈfɑːðər/",pos:"n.",meaning:"父亲",sentence:"His father works in a bank.",translation:"他父亲在银行工作。"},
  {word:"student",phonetic:"/ˈstuːdnt/",pos:"n.",meaning:"学生",sentence:"Are you a new student?",translation:"你是新学生吗？"},
  {word:"book",phonetic:"/bʊk/",pos:"n.",meaning:"书",sentence:"I love reading this book.",translation:"我喜欢读这本书。"},
  {word:"and",phonetic:"/ænd/",pos:"conj.",meaning:"和，并且",sentence:"You and I are friends.",translation:"你和我是朋友。"},
  {word:"like",phonetic:"/laɪk/",pos:"v., prep.",meaning:"喜欢，像",sentence:"I like apples.",translation:"我喜欢苹果。"},
  {word:"we",phonetic:"/wiː/",pos:"pron.",meaning:"我们",sentence:"We are going home.",translation:"我们正要回家。"},
  {word:"our",phonetic:"/ˈaʊər/",pos:"pron.",meaning:"我们的",sentence:"This is our house.",translation:"这是我们的房子。"},
  {word:"they",phonetic:"/ðeɪ/",pos:"pron.",meaning:"他们",sentence:"They are playing soccer.",translation:"他们正在踢足球。"},
  {word:"their",phonetic:"/ðer/",pos:"pron.",meaning:"他们的",sentence:"Their car is red.",translation:"他们的车是红色的。"},
  {word:"black",phonetic:"/blæk/",pos:"adj., n.",meaning:"黑色的，黑色",sentence:"I have a black cat.",translation:"我有一只黑猫。"},
  {word:"blue",phonetic:"/bluː/",pos:"adj., n.",meaning:"蓝色的，蓝色",sentence:"The sky is blue.",translation:"天空是蓝色的。"},
  {word:"white",phonetic:"/waɪt/",pos:"adj., n.",meaning:"白色的，白色",sentence:"She is wearing a white dress.",translation:"她穿着一件白色的裙子。"},
  {word:"red",phonetic:"/red/",pos:"adj., n.",meaning:"红色的，红色",sentence:"I want the red apple.",translation:"我想要那个红苹果。"},
  {word:"green",phonetic:"/ɡriːn/",pos:"adj., n.",meaning:"绿色的，绿色",sentence:"The grass is green.",translation:"草是绿色的。"},
  {word:"computer",phonetic:"/kəmˈpjuːtər/",pos:"n.",meaning:"电脑",sentence:"My computer is new.",translation:"我的电脑是新的。"},
  {word:"room",phonetic:"/ruːm/",pos:"n.",meaning:"房间",sentence:"Clean your room please.",translation:"请打扫你的房间。"},
  {word:"phone",phonetic:"/foʊn/",pos:"n.",meaning:"电话，手机",sentence:"Where is my phone?",translation:"我的手机在哪里？"},
  {word:"big",phonetic:"/bɪɡ/",pos:"adj.",meaning:"大的",sentence:"That is a big house.",translation:"那是一所大房子。"},
  {word:"house",phonetic:"/haʊs/",pos:"n.",meaning:"房子",sentence:"They bought a new house.",translation:"他们买了一所新房子。"},
  {word:"small",phonetic:"/smɔːl/",pos:"adj.",meaning:"小的",sentence:"The shoes are too small.",translation:"这双鞋太小了。"},
  {word:"short",phonetic:"/ʃɔːrt/",pos:"adj.",meaning:"短的，矮的",sentence:"He is short but strong.",translation:"他很矮但是很壮。"},
  {word:"long",phonetic:"/lɔːŋ/",pos:"adj.",meaning:"长的",sentence:"She has long hair.",translation:"她有长头发。"},
  {word:"spring",phonetic:"/sprɪŋ/",pos:"n.",meaning:"春天",sentence:"Flowers bloom in spring.",translation:"花在春天开放。"},
  {word:"summer",phonetic:"/ˈsʌmər/",pos:"n.",meaning:"夏天",sentence:"It is hot in summer.",translation:"夏天很热。"},
  {word:"fall",phonetic:"/fɔːl/",pos:"n., v.",meaning:"秋天，落下",sentence:"Leaves turn yellow in fall.",translation:"叶子在秋天变黄。"},
  {word:"winter",phonetic:"/ˈwɪntər/",pos:"n.",meaning:"冬天",sentence:"Winter is coming.",translation:"冬天来了。"},
  {word:"is",phonetic:"/ɪz/",pos:"v.",meaning:"是",sentence:"He is a doctor.",translation:"他是一名医生。"},
  {word:"or",phonetic:"/ɔːr/",pos:"conj.",meaning:"或者",sentence:"Tea or coffee?",translation:"茶还是咖啡？"},
  {word:"more",phonetic:"/mɔːr/",pos:"adv., adj.",meaning:"更多",sentence:"I need more time.",translation:"我需要更多时间。"},
  {word:"less",phonetic:"/les/",pos:"adv., adj.",meaning:"更少",sentence:"Eat less sugar.",translation:"少吃糖。"},
  {word:"hot",phonetic:"/hɑːt/",pos:"adj.",meaning:"热的",sentence:"The soup is very hot.",translation:"汤很烫。"},
  {word:"cold",phonetic:"/koʊld/",pos:"adj., n.",meaning:"冷的，感冒",sentence:"It is cold outside.",translation:"外面很冷。"},
  {word:"coffee",phonetic:"/ˈkɔːfi/",pos:"n.",meaning:"咖啡",sentence:"I drink coffee every morning.",translation:"我每天早上喝咖啡。"},
  {word:"juice",phonetic:"/dʒuːs/",pos:"n.",meaning:"果汁",sentence:"Orange juice is sweet.",translation:"橙汁很甜。"},
  {word:"drink",phonetic:"/drɪŋk/",pos:"v., n.",meaning:"喝，饮料",sentence:"Drink some water.",translation:"喝点水。"},
  {word:"water",phonetic:"/ˈwɔːtər/",pos:"n.",meaning:"水",sentence:"Can I have some water?",translation:"能给我点水吗？"},
  {word:"tea",phonetic:"/tiː/",pos:"n.",meaning:"茶",sentence:"British people love tea.",translation:"英国人喜欢茶。"},
  {word:"yes",phonetic:"/jes/",pos:"adv.",meaning:"是的",sentence:"Yes, I understand.",translation:"是的，我明白了。"},
  {word:"a",phonetic:"/ə/",pos:"art.",meaning:"一个",sentence:"I have a pen.",translation:"我有一支笔。"},
  {word:"are",phonetic:"/ɑːr/",pos:"v.",meaning:"是",sentence:"They are happy.",translation:"他们很快乐。"},
  {word:"am",phonetic:"/æm/",pos:"v.",meaning:"是",sentence:"I am ready.",translation:"我准备好了。"},
  {word:"hello",phonetic:"/həˈloʊ/",pos:"int.",meaning:"你好",sentence:"Hello, how are you?",translation:"你好，你好吗？"},
  {word:"good",phonetic:"/ɡʊd/",pos:"adj.",meaning:"好的",sentence:"Have a good day.",translation:"祝你有美好的一天。"},
  {word:"he",phonetic:"/hiː/",pos:"pron.",meaning:"他",sentence:"He is my brother.",translation:"他是我的哥哥。"},
  {word:"she",phonetic:"/ʃiː/",pos:"pron.",meaning:"她",sentence:"She is very smart.",translation:"她很聪明。"},
  {word:"woman",phonetic:"/ˈwʊmən/",pos:"n.",meaning:"女人",sentence:"She is a kind woman.",translation:"她是一个善良的女人。"},
  {word:"girl",phonetic:"/ɡɜːrl/",pos:"n.",meaning:"女孩",sentence:"The girl is dancing.",translation:"那个女孩在跳舞。"},
  {word:"man",phonetic:"/mæn/",pos:"n.",meaning:"男人",sentence:"He is a strong man.",translation:"他是一个强壮的男人。"},
  {word:"boy",phonetic:"/bɔɪ/",pos:"n.",meaning:"男孩",sentence:"The boy is playing.",translation:"那个男孩在玩耍。"},
  {word:"evening",phonetic:"/ˈiːvnɪŋ/",pos:"n.",meaning:"晚上",sentence:"Good evening!",translation:"晚上好！"},
  {word:"morning",phonetic:"/ˈmɔːrnɪŋ/",pos:"n.",meaning:"早晨",sentence:"Good morning!",translation:"早上好！"},
  {word:"look",phonetic:"/lʊk/",pos:"v.",meaning:"看",sentence:"Look at the sky.",translation:"看天空。"},
  {word:"bag",phonetic:"/bæɡ/",pos:"n.",meaning:"包",sentence:"Where is my bag?",translation:"我的包在哪里？"},
  {word:"by",phonetic:"/baɪ/",pos:"prep.",meaning:"在...旁边，通过",sentence:"He stood by the window.",translation:"他站在窗户旁边。"},
  {word:"this",phonetic:"/ðɪs/",pos:"pron., adj.",meaning:"这个",sentence:"This is my friend.",translation:"这是我的朋友。"},
  {word:"thanks",phonetic:"/θæŋks/",pos:"n., int.",meaning:"谢谢",sentence:"Thanks for your help.",translation:"谢谢你的帮助。"},
  {word:"road",phonetic:"/roʊd/",pos:"n.",meaning:"路",sentence:"Cross the road carefully.",translation:"小心过马路。"},
  {word:"coat",phonetic:"/koʊt/",pos:"n.",meaning:"外套",sentence:"Put on your coat.",translation:"穿上你的外套。"},
  {word:"watch",phonetic:"/wɑːtʃ/",pos:"n., v.",meaning:"手表，观看",sentence:"I like to watch movies.",translation:"我喜欢看电影。"},
  {word:"no",phonetic:"/noʊ/",pos:"adv., adj.",meaning:"不，没有",sentence:"No, I don't think so.",translation:"不，我不这么认为。"},
  {word:"wallet",phonetic:"/ˈwɑːlɪt/",pos:"n.",meaning:"钱包",sentence:"I lost my wallet.",translation:"我丢了我的钱包。"},
  {word:"not",phonetic:"/nɑːt/",pos:"adv.",meaning:"不",sentence:"I am not tired.",translation:"我不累。"},
  {word:"camera",phonetic:"/ˈkæmərə/",pos:"n.",meaning:"照相机",sentence:"This camera is expensive.",translation:"这个相机很贵。"},
  {word:"wall",phonetic:"/wɔːl/",pos:"n.",meaning:"墙",sentence:"The wall is white.",translation:"这堵墙是白色的。"},
  {word:"excuse me",phonetic:"/ɪkˈskjuːz miː/",pos:"phr.",meaning:"打扰一下，借过",sentence:"Excuse me, where is the restroom?",translation:"打扰一下，洗手间在哪里？"},
  {word:"at",phonetic:"/æt/",pos:"prep.",meaning:"在",sentence:"I am at home.",translation:"我在家。"},
  {word:"new",phonetic:"/nuː/",pos:"adj.",meaning:"新的",sentence:"I have a new car.",translation:"我有一辆新车。"},
  {word:"nice",phonetic:"/naɪs/",pos:"adj.",meaning:"美好的，友好的",sentence:"Have a nice day.",translation:"祝你有美好的一天。"},
  {word:"from",phonetic:"/frʌm/",pos:"prep.",meaning:"来自",sentence:"Where are you from?",translation:"你来自哪里？"},
  {word:"meat",phonetic:"/miːt/",pos:"n.",meaning:"肉",sentence:"I don't eat meat.",translation:"我不吃肉。"},
  {word:"land",phonetic:"/lænd/",pos:"n., v.",meaning:"陆地，着陆",sentence:"The plane will land soon.",translation:"飞机很快就要降落了。"},
  {word:"China",phonetic:"/ˈtʃaɪnə/",pos:"n.",meaning:"中国",sentence:"I live in China.",translation:"我住在中国。"},
  {word:"speak",phonetic:"/spiːk/",pos:"v.",meaning:"说，讲",sentence:"Can you speak English?",translation:"你会说英语吗？"},
  {word:"a little",phonetic:"/ə ˈlɪtl/",pos:"phr.",meaning:"一点点",sentence:"I speak a little Spanish.",translation:"我会说一点西班牙语。"},
  {word:"America",phonetic:"/əˈmerɪkə/",pos:"n.",meaning:"美国",sentence:"He is from America.",translation:"他来自美国。"},
  {word:"sea",phonetic:"/siː/",pos:"n.",meaning:"海",sentence:"The sea is blue.",translation:"大海是蓝色的。"},
  {word:"please",phonetic:"/pliːz/",pos:"int.",meaning:"请",sentence:"Sit down, please.",translation:"请坐。"},
  {word:"bye",phonetic:"/baɪ/",pos:"int.",meaning:"再见",sentence:"Bye, see you later.",translation:"再见，回头见。"},
  {word:"salad",phonetic:"/ˈsæləd/",pos:"n.",meaning:"沙拉",sentence:"I like fruit salad.",translation:"我喜欢水果沙拉。"},
  {word:"pork",phonetic:"/pɔːrk/",pos:"n.",meaning:"猪肉",sentence:"We had pork for dinner.",translation:"我们晚餐吃了猪肉。"},
  {word:"sandwich",phonetic:"/ˈsænwɪtʃ/",pos:"n.",meaning:"三明治",sentence:"I ate a sandwich for lunch.",translation:"我午餐吃了一个三明治。"},
  {word:"would you like",phonetic:"/wʊd ju laɪk/",pos:"phr.",meaning:"你想要...吗",sentence:"Would you like some tea?",translation:"你想要点茶吗？"},
  {word:"I'd like",phonetic:"/aɪd laɪk/",pos:"phr.",meaning:"我想要",sentence:"I'd like a coffee, please.",translation:"请给我一杯咖啡。"},
  {word:"afternoon",phonetic:"/ˌæftərˈnuːn/",pos:"n.",meaning:"下午",sentence:"Good afternoon.",translation:"下午好。"},
  {word:"pay",phonetic:"/peɪ/",pos:"v.",meaning:"支付",sentence:"I will pay for the meal.",translation:"我会付饭钱。"},
  {word:"chair",phonetic:"/tʃer/",pos:"n.",meaning:"椅子",sentence:"Please take a chair.",translation:"请拿一把椅子。"},
  {word:"cheese",phonetic:"/tʃiːz/",pos:"n.",meaning:"奶酪",sentence:"Mice like cheese.",translation:"老鼠喜欢奶酪。"},
  {word:"chicken",phonetic:"/ˈtʃɪkɪn/",pos:"n.",meaning:"鸡肉，鸡",sentence:"Fried chicken is tasty.",translation:"炸鸡很好吃。"},
  {word:"cup",phonetic:"/kʌp/",pos:"n.",meaning:"杯子",sentence:"I would like a cup of tea.",translation:"我想要一杯茶。"},
  {word:"have",phonetic:"/hæv/",pos:"v.",meaning:"有，吃",sentence:"I have a dream.",translation:"我有一个梦想。"},
  {word:"day",phonetic:"/deɪ/",pos:"n.",meaning:"天，白天",sentence:"What day is it today?",translation:"今天是星期几？"},
  {word:"mall",phonetic:"/mɔːl/",pos:"n.",meaning:"购物中心",sentence:"Let's go to the mall.",translation:"我们去购物中心吧。"},
  {word:"taxi driver",phonetic:"/ˈtæksi ˈdraɪvər/",pos:"n.",meaning:"出租车司机",sentence:"The taxi driver is friendly.",translation:"那个出租车司机很友好。"},
  {word:"friend",phonetic:"/frend/",pos:"n.",meaning:"朋友",sentence:"He is my best friend.",translation:"他是我最好的朋友。"},
  {word:"lock",phonetic:"/lɑːk/",pos:"v., n.",meaning:"锁",sentence:"Don't forget to lock the door.",translation:"别忘了锁门。"},
  {word:"doctor",phonetic:"/ˈdɑːktər/",pos:"n.",meaning:"医生",sentence:"You should see a doctor.",translation:"你应该去看医生。"},
  {word:"bath",phonetic:"/bæθ/",pos:"n.",meaning:"洗澡",sentence:"I take a bath every day.",translation:"我每天都洗澡。"},
  {word:"math",phonetic:"/mæθ/",pos:"n.",meaning:"数学",sentence:"Math is difficult for me.",translation:"数学对我来说很难。"},
  {word:"game",phonetic:"/ɡeɪm/",pos:"n.",meaning:"游戏",sentence:"Let's play a game.",translation:"我们玩个游戏吧。"},
  {word:"boring",phonetic:"/ˈbɔːrɪŋ/",pos:"adj.",meaning:"无聊的",sentence:"This movie is boring.",translation:"这部电影很无聊。"},
  {word:"shirt",phonetic:"/ʃɜːrt/",pos:"n.",meaning:"衬衫",sentence:"He is wearing a blue shirt.",translation:"他穿着一件蓝衬衫。"},
  {word:"welcome",phonetic:"/ˈwelkəm/",pos:"adj., int.",meaning:"受欢迎的，欢迎",sentence:"Welcome to our home.",translation:"欢迎来我们家。"},
  {word:"need",phonetic:"/niːd/",pos:"v.",meaning:"需要",sentence:"I need your help.",translation:"我需要你的帮助。"},
  {word:"jacket",phonetic:"/ˈdʒækɪt/",pos:"n.",meaning:"夹克",sentence:"Wear a jacket, it's cold.",translation:"穿上夹克，外面冷。"},
  {word:"expensive",phonetic:"/ɪkˈspensɪv/",pos:"adj.",meaning:"昂贵的",sentence:"That car is very expensive.",translation:"那辆车很贵。"},
  {word:"cap",phonetic:"/kæp/",pos:"n.",meaning:"鸭舌帽",sentence:"He is wearing a baseball cap.",translation:"他戴着一顶棒球帽。"},
  {word:"sat",phonetic:"/sæt/",pos:"v.",meaning:"坐(sit的过去式)",sentence:"He sat on the chair.",translation:"他坐在椅子上。"},
  {word:"dollar",phonetic:"/ˈdɑːlər/",pos:"n.",meaning:"美元",sentence:"It costs one dollar.",translation:"它花费一美元。"},
  {word:"much",phonetic:"/mʌtʃ/",pos:"adv., adj.",meaning:"许多",sentence:"How much is it?",translation:"多少钱？"},
  {word:"one",phonetic:"/wʌn/",pos:"num.",meaning:"一",sentence:"I have one sister.",translation:"我有一个姐姐。"},
  {word:"two",phonetic:"/tuː/",pos:"num.",meaning:"二",sentence:"Two tickets please.",translation:"请给我两张票。"},
  {word:"three",phonetic:"/θriː/",pos:"num.",meaning:"三",sentence:"I have three cats.",translation:"我有三只猫。"},
  {word:"four",phonetic:"/fɔːr/",pos:"num.",meaning:"四",sentence:"There are four seasons.",translation:"一年有四季。"},
  {word:"five",phonetic:"/faɪv/",pos:"num.",meaning:"五",sentence:"Give me five.",translation:"击掌。"},
  {word:"six",phonetic:"/sɪks/",pos:"num.",meaning:"六",sentence:"He is six years old.",translation:"他六岁了。"},
  {word:"seven",phonetic:"/ˈsevn/",pos:"num.",meaning:"七",sentence:"Seven is a lucky number.",translation:"七是个幸运数字。"},
  {word:"eight",phonetic:"/eɪt/",pos:"num.",meaning:"八",sentence:"I wake up at eight.",translation:"我八点醒来。"},
  {word:"nine",phonetic:"/naɪn/",pos:"num.",meaning:"九",sentence:"It is nine o'clock.",translation:"现在是九点钟。"},
  {word:"ten",phonetic:"/ten/",pos:"num.",meaning:"十",sentence:"Count to ten.",translation:"数到十。"},
  {word:"one hundred",phonetic:"/wʌn ˈhʌndrəd/",pos:"num.",meaning:"一百",sentence:"I have one hundred dollars.",translation:"我有一百美元。"},
  {word:"how",phonetic:"/haʊ/",pos:"adv.",meaning:"如何，怎样",sentence:"How are you?",translation:"你好吗？"},
  {word:"her",phonetic:"/hɜːr/",pos:"pron.",meaning:"她的",sentence:"This is her bag.",translation:"这是她的包。"},
  {word:"sister",phonetic:"/ˈsɪstər/",pos:"n.",meaning:"姐妹",sentence:"My sister is a nurse.",translation:"我的姐姐是一名护士。"},
  {word:"boyfriend",phonetic:"/ˈbɔɪfrend/",pos:"n.",meaning:"男朋友",sentence:"She loves her boyfriend.",translation:"她爱她的男朋友。"},
  {word:"brother",phonetic:"/ˈbrʌðər/",pos:"n.",meaning:"兄弟",sentence:"I play with my brother.",translation:"我和我哥哥一起玩。"},
  {word:"girlfriend",phonetic:"/ˈɡɜːrlfrend/",pos:"n.",meaning:"女朋友",sentence:"His girlfriend is pretty.",translation:"他的女朋友很漂亮。"},
  {word:"his",phonetic:"/hɪz/",pos:"pron.",meaning:"他的",sentence:"His name is John.",translation:"他的名字叫约翰。"},
  {word:"husband",phonetic:"/ˈhʌzbənd/",pos:"n.",meaning:"丈夫",sentence:"Her husband is a pilot.",translation:"她的丈夫是一名飞行员。"},
  {word:"wife",phonetic:"/waɪf/",pos:"n.",meaning:"妻子",sentence:"He loves his wife very much.",translation:"他非常爱他的妻子。"},
  {word:"tall",phonetic:"/tɔːl/",pos:"adj.",meaning:"高的",sentence:"He is very tall.",translation:"他很高。"},
  {word:"rich",phonetic:"/rɪtʃ/",pos:"adj.",meaning:"富有的",sentence:"He is a rich man.",translation:"他是一个有钱人。"},
  {word:"life",phonetic:"/laɪf/",pos:"n.",meaning:"生活，生命",sentence:"Life is beautiful.",translation:"生活是美好的。"},
  {word:"smart",phonetic:"/smɑːrt/",pos:"adj.",meaning:"聪明的",sentence:"She is a smart student.",translation:"她是一个聪明的学生。"},
  {word:"son",phonetic:"/sʌn/",pos:"n.",meaning:"儿子",sentence:"My son likes football.",translation:"我儿子喜欢足球。"},
  {word:"dear",phonetic:"/dɪr/",pos:"adj.",meaning:"亲爱的",sentence:"Dear friend, how are you?",translation:"亲爱的朋友，你好吗？"},
  {word:"years old",phonetic:"/jɪrz oʊld/",pos:"phr.",meaning:"岁",sentence:"I am twenty years old.",translation:"我二十岁。"},
  {word:"daughter",phonetic:"/ˈdɔːtər/",pos:"n.",meaning:"女儿",sentence:"His daughter is cute.",translation:"他的女儿很可爱。"},
  {word:"beer",phonetic:"/bɪr/",pos:"n.",meaning:"啤酒",sentence:"He drinks beer.",translation:"他喝啤酒。"},
  {word:"pizza",phonetic:"/ˈpiːtsə/",pos:"n.",meaning:"披萨",sentence:"I love cheese pizza.",translation:"我喜欢芝士披萨。"},
  {word:"of",phonetic:"/əv/",pos:"prep.",meaning:"...的",sentence:"A cup of tea.",translation:"一杯茶。"},
  {word:"cheers",phonetic:"/tʃɪrz/",pos:"int.",meaning:"干杯",sentence:"Cheers to our friendship!",translation:"为我们的友谊干杯！"},
  {word:"goodbye",phonetic:"/ˌɡʊdˈbaɪ/",pos:"int.",meaning:"再见",sentence:"Goodbye, take care.",translation:"再见，保重。"},
  {word:"with",phonetic:"/wɪð/",pos:"prep.",meaning:"和...一起",sentence:"Come with me.",translation:"跟我来。"},
  {word:"milk",phonetic:"/mɪlk/",pos:"n.",meaning:"牛奶",sentence:"I drink milk every day.",translation:"我每天喝牛奶。"},
  {word:"sugar",phonetic:"/ˈʃʊɡər/",pos:"n.",meaning:"糖",sentence:"Do you take sugar in your coffee?",translation:"你喝咖啡加糖吗？"},
  {word:"restaurant",phonetic:"/ˈrestərɑːnt/",pos:"n.",meaning:"餐馆",sentence:"This is a good restaurant.",translation:"这是一家好餐馆。"},
  {word:"table",phonetic:"/ˈteɪbl/",pos:"n.",meaning:"桌子",sentence:"The book is on the table.",translation:"书在桌子上。"},
  {word:"check",phonetic:"/tʃek/",pos:"v., n.",meaning:"检查，账单",sentence:"Can I have the check please?",translation:"请给我结账好吗？"},
  {word:"menu",phonetic:"/ˈmenjuː/",pos:"n.",meaning:"菜单",sentence:"Can I see the menu?",translation:"我能看下菜单吗？"},
  {word:"for",phonetic:"/fɔːr/",pos:"prep.",meaning:"为了",sentence:"This gift is for you.",translation:"这个礼物是给你的。"},
  {word:"important",phonetic:"/ɪmˈpɔːrtnt/",pos:"adj.",meaning:"重要的",sentence:"This is an important meeting.",translation:"这是一个重要的会议。"},
  {word:"cool",phonetic:"/kuːl/",pos:"adj.",meaning:"凉爽的，酷的",sentence:"The weather is cool today.",translation:"今天天气很凉爽。"},
  {word:"exact",phonetic:"/ɪɡˈzækt/",pos:"adj.",meaning:"确切的",sentence:"What is the exact time?",translation:"确切时间是多少？"},
  {word:"question",phonetic:"/ˈkwestʃən/",pos:"n.",meaning:"问题",sentence:"I have a question.",translation:"我有一个问题。"},
  {word:"many",phonetic:"/ˈmeni/",pos:"adj., pron.",meaning:"许多",sentence:"I have many friends.",translation:"我有许多朋友。"},
  {word:"school",phonetic:"/skuːl/",pos:"n.",meaning:"学校",sentence:"I go to school by bus.",translation:"我乘公交车去上学。"},
  {word:"pass",phonetic:"/pæs/",pos:"v.",meaning:"通过，传递",sentence:"Please pass the salt.",translation:"请把盐递给我。"},
  {word:"class",phonetic:"/klæs/",pos:"n.",meaning:"班级，课",sentence:"The class starts at 8.",translation:"课程8点开始。"},
  {word:"glass",phonetic:"/ɡlæs/",pos:"n.",meaning:"玻璃，玻璃杯",sentence:"Give me a glass of water.",translation:"给我一杯水。"},
  {word:"difficult",phonetic:"/ˈdɪfɪkəlt/",pos:"adj.",meaning:"困难的",sentence:"The exam was difficult.",translation:"考试很难。"},
  {word:"has",phonetic:"/hæz/",pos:"v.",meaning:"有(第三人称单数)",sentence:"He has a dog.",translation:"他有一只狗。"},
  {word:"exam",phonetic:"/ɪɡˈzæm/",pos:"n.",meaning:"考试",sentence:"I passed the exam.",translation:"我通过了考试。"},
  {word:"easy",phonetic:"/ˈiːzi/",pos:"adj.",meaning:"容易的",sentence:"This game is easy.",translation:"这个游戏很容易。"},
  {word:"today",phonetic:"/təˈdeɪ/",pos:"n., adv.",meaning:"今天",sentence:"How are you today?",translation:"你今天好吗？"},
  {word:"an",phonetic:"/ən/",pos:"art.",meaning:"一个",sentence:"I want an apple.",translation:"我想要一个苹果。"},
  {word:"these",phonetic:"/ðiːz/",pos:"pron.",meaning:"这些",sentence:"These are my shoes.",translation:"这些是我的鞋子。"},
  {word:"favorite",phonetic:"/ˈfeɪvərɪt/",pos:"adj., n.",meaning:"最喜欢的",sentence:"Red is my favorite color.",translation:"红色是我最喜欢的颜色。"},
  {word:"color",phonetic:"/ˈkʌlər/",pos:"n.",meaning:"颜色",sentence:"What color do you like?",translation:"你喜欢什么颜色？"},
  {word:"beautiful",phonetic:"/ˈbjuːtɪfl/",pos:"adj.",meaning:"美丽的",sentence:"She is very beautiful.",translation:"她非常美丽。"},
  {word:"orange",phonetic:"/ˈɔːrɪndʒ/",pos:"n., adj.",meaning:"橙子，橙色的",sentence:"I like orange juice.",translation:"我喜欢橙汁。"},
  {word:"dress",phonetic:"/dres/",pos:"n., v.",meaning:"连衣裙，穿衣",sentence:"She bought a new dress.",translation:"她买了一条新裙子。"},
  {word:"too",phonetic:"/tuː/",pos:"adv.",meaning:"太，也",sentence:"It is too hot.",translation:"太热了。"},
  {word:"really",phonetic:"/ˈriːəli/",pos:"adv.",meaning:"真地",sentence:"I really like you.",translation:"我真的很喜欢你。"},
  {word:"song",phonetic:"/sɔːŋ/",pos:"n.",meaning:"歌曲",sentence:"Sing a song.",translation:"唱首歌。"},
  {word:"pants",phonetic:"/pænts/",pos:"n.",meaning:"裤子",sentence:"These pants are too long.",translation:"这条裤子太长了。"},
  {word:"shoe",phonetic:"/ʃuː/",pos:"n.",meaning:"鞋",sentence:"I lost one shoe.",translation:"我丢了一只鞋。"},
  {word:"key",phonetic:"/kiː/",pos:"n.",meaning:"钥匙",sentence:"I lost my car key.",translation:"我丢了我的车钥匙。"},
  {word:"bar",phonetic:"/bɑːr/",pos:"n.",meaning:"酒吧",sentence:"Let's meet at the bar.",translation:"我们在酒吧见面吧。"},
  {word:"that's",phonetic:"/ðæts/",pos:"contr.",meaning:"那是",sentence:"That's a good idea.",translation:"那是个好主意。"},
  {word:"you're welcome",phonetic:"/jʊr ˈwelkəm/",pos:"phr.",meaning:"不客气",sentence:"Thank you. You're welcome.",translation:"谢谢你。不客气。"},
  {word:"car",phonetic:"/kɑːr/",pos:"n.",meaning:"汽车",sentence:"He drives a fast car.",translation:"他开着一辆快车。"},
  {word:"except",phonetic:"/ɪkˈsept/",pos:"prep.",meaning:"除了...之外",sentence:"Everyone is here except Tom.",translation:"除了汤姆，大家都在这里。"},
  {word:"very",phonetic:"/ˈveri/",pos:"adv.",meaning:"非常",sentence:"Thank you very much.",translation:"非常感谢。"},
  {word:"parent",phonetic:"/ˈperənt/",pos:"n.",meaning:"父母亲",sentence:"My parent is strict.",translation:"我的父（母）亲很严格。"},
  {word:"friendly",phonetic:"/ˈfrendli/",pos:"adj.",meaning:"友好的",sentence:"The people here are friendly.",translation:"这里的人很友好。"},
  {word:"person",phonetic:"/ˈpɜːrsn/",pos:"n.",meaning:"人",sentence:"She is a nice person.",translation:"她是一个好人。"},
  {word:"where",phonetic:"/wer/",pos:"adv.",meaning:"哪里",sentence:"Where do you live?",translation:"你住在哪里？"},
  {word:"here",phonetic:"/hɪr/",pos:"adv.",meaning:"这里",sentence:"Come here please.",translation:"请到这里来。"},
  {word:"best",phonetic:"/best/",pos:"adj., adv.",meaning:"最好的",sentence:"You are the best.",translation:"你是最好的。"},
  {word:"happy",phonetic:"/ˈhæpi/",pos:"adj.",meaning:"快乐的",sentence:"I am very happy today.",translation:"我今天很快乐。"},
  {word:"family",phonetic:"/ˈfæməli/",pos:"n.",meaning:"家庭",sentence:"I love my family.",translation:"我爱我的家庭。"},
  {word:"always",phonetic:"/ˈɔːlweɪz/",pos:"adv.",meaning:"总是",sentence:"He is always late.",translation:"他总是迟到。"},
  {word:"busy",phonetic:"/ˈbɪzi/",pos:"adj.",meaning:"忙碌的",sentence:"I am busy right now.",translation:"我现在很忙。"},
  {word:"love",phonetic:"/lʌv/",pos:"v., n.",meaning:"爱",sentence:"I love you.",translation:"我爱你。"},
  {word:"that",phonetic:"/ðæt/",pos:"pron., conj.",meaning:"那个",sentence:"What is that?",translation:"那是什么？"},
  {word:"funny",phonetic:"/ˈfʌni/",pos:"adj.",meaning:"好笑的，滑稽的",sentence:"He tells funny jokes.",translation:"他讲的笑话很好笑。"},
  {word:"sunny",phonetic:"/ˈsʌni/",pos:"adj.",meaning:"晴朗的",sentence:"It is a sunny day.",translation:"今天是个晴天。"},
  {word:"bad",phonetic:"/bæd/",pos:"adj.",meaning:"坏的",sentence:"That is a bad idea.",translation:"那是个坏主意。"},
  {word:"do",phonetic:"/duː/",pos:"v.",meaning:"做",sentence:"Do your homework.",translation:"做你的家庭作业。"},
  {word:"country",phonetic:"/ˈkʌntri/",pos:"n.",meaning:"国家，乡村",sentence:"Which country are you from?",translation:"你来自哪个国家？"},
  {word:"Japan",phonetic:"/dʒəˈpæn/",pos:"n.",meaning:"日本",sentence:"Tokyo is in Japan.",translation:"东京在日本。"},
  {word:"live",phonetic:"/lɪv/",pos:"v.",meaning:"居住",sentence:"I live in New York.",translation:"我住在纽约。"},
  {word:"in",phonetic:"/ɪn/",pos:"prep.",meaning:"在...里面",sentence:"The cat is in the box.",translation:"猫在盒子里。"},
  {word:"language",phonetic:"/ˈlæŋɡwɪdʒ/",pos:"n.",meaning:"语言",sentence:"English is a global language.",translation:"英语是一门全球性语言。"},
  {word:"don't",phonetic:"/doʊnt/",pos:"contr.",meaning:"不(do not)",sentence:"I don't know.",translation:"我不知道。"},
  {word:"but",phonetic:"/bʌt/",pos:"conj.",meaning:"但是",sentence:"I am tired but happy.",translation:"我很累但是很开心。"},
  {word:"Spanish",phonetic:"/ˈspænɪʃ/",pos:"adj., n.",meaning:"西班牙语，西班牙的",sentence:"I am learning Spanish.",translation:"我正在学习西班牙语。"},
  {word:"cut",phonetic:"/kʌt/",pos:"v.",meaning:"切，剪",sentence:"Cut the cake please.",translation:"请切蛋糕。"},
  {word:"know",phonetic:"/noʊ/",pos:"v.",meaning:"知道",sentence:"Do you know him?",translation:"你认识他吗？"},
  {word:"address",phonetic:"/ˈædres/",pos:"n.",meaning:"地址",sentence:"What is your address?",translation:"你的地址是什么？"},
  {word:"no problem",phonetic:"/noʊ ˈprɑːbləm/",pos:"phr.",meaning:"没问题",sentence:"Can you help me? No problem.",translation:"你能帮我吗？没问题。"},
  {word:"sorry",phonetic:"/ˈsɑːri/",pos:"adj., int.",meaning:"对不起",sentence:"I am sorry for being late.",translation:"对不起我迟到了。"},
  {word:"pet",phonetic:"/pet/",pos:"n.",meaning:"宠物",sentence:"Do you have a pet?",translation:"你有宠物吗？"},
  {word:"name",phonetic:"/neɪm/",pos:"n.",meaning:"名字",sentence:"My name is Alice.",translation:"我的名字叫爱丽丝。"},
  {word:"understand",phonetic:"/ˌʌndərˈstænd/",pos:"v.",meaning:"理解",sentence:"I don't understand.",translation:"我不明白。"},
  {word:"email",phonetic:"/ˈiːmeɪl/",pos:"n.",meaning:"电子邮件",sentence:"Send me an email.",translation:"给我发个邮件。"},
  {word:"hospital",phonetic:"/ˈhɑːspɪtl/",pos:"n.",meaning:"医院",sentence:"He works in a hospital.",translation:"他在医院工作。"},
  {word:"stand",phonetic:"/stænd/",pos:"v.",meaning:"站立",sentence:"Please stand up.",translation:"请站起来。"},
  {word:"work",phonetic:"/wɜːrk/",pos:"v., n.",meaning:"工作",sentence:"I work at a bank.",translation:"我在银行工作。"},
  {word:"together",phonetic:"/təˈɡeðər/",pos:"adv.",meaning:"一起",sentence:"Let's go together.",translation:"我们一起去吧。"},
  {word:"what do you do",phonetic:"/wʌt du ju du/",pos:"phr.",meaning:"你是做什么工作的",sentence:"What do you do? I am a teacher.",translation:"你是做什么的？我是个老师。"},
  {word:"office",phonetic:"/ˈɔːfɪs/",pos:"n.",meaning:"办公室",sentence:"My office is nearby.",translation:"我的办公室在附近。"},
  {word:"meeting",phonetic:"/ˈmiːtɪŋ/",pos:"n.",meaning:"会议",sentence:"I have a meeting at 10.",translation:"我十点有个会。"},
  {word:"bank",phonetic:"/bæŋk/",pos:"n.",meaning:"银行",sentence:"I need to go to the bank.",translation:"我得去银行。"},
  {word:"job",phonetic:"/dʒɑːb/",pos:"n.",meaning:"工作",sentence:"I love my job.",translation:"我热爱我的工作。"},
  {word:"lot",phonetic:"/lɑːt/",pos:"n.",meaning:"许多",sentence:"Thanks a lot.",translation:"多谢。"},
  {word:"beach",phonetic:"/biːtʃ/",pos:"n.",meaning:"海滩",sentence:"Let's go to the beach.",translation:"我们去海滩吧。"},
  {word:"tonight",phonetic:"/təˈnaɪt/",pos:"adv., n.",meaning:"今晚",sentence:"See you tonight.",translation:"今晚见。"},
  {word:"study",phonetic:"/ˈstʌdi/",pos:"v.",meaning:"学习",sentence:"I study English every day.",translation:"我每天学习英语。"},
  {word:"teach",phonetic:"/tiːtʃ/",pos:"v.",meaning:"教",sentence:"She teaches math.",translation:"她教数学。"},
  {word:"university",phonetic:"/ˌjuːnɪˈvɜːrsəti/",pos:"n.",meaning:"大学",sentence:"He goes to university.",translation:"他上大学。"},
  {word:"on",phonetic:"/ɑːn/",pos:"prep.",meaning:"在...上面",sentence:"The pen is on the desk.",translation:"笔在桌子上。"},
  {word:"Sunday",phonetic:"/ˈsʌndeɪ/",pos:"n.",meaning:"星期日",sentence:"I rest on Sunday.",translation:"我星期日休息。"},
  {word:"Saturday",phonetic:"/ˈsætərdeɪ/",pos:"n.",meaning:"星期六",sentence:"The party is on Saturday.",translation:"聚会在星期六。"},
  {word:"Friday",phonetic:"/ˈfraɪdeɪ/",pos:"n.",meaning:"星期五",sentence:"Thank God it's Friday.",translation:"谢天谢地今天是周五。"},
  {word:"Thursday",phonetic:"/ˈθɜːrzdeɪ/",pos:"n.",meaning:"星期四",sentence:"We meet on Thursday.",translation:"我们周四见面。"},
  {word:"Wednesday",phonetic:"/ˈwenzdeɪ/",pos:"n.",meaning:"星期三",sentence:"Today is Wednesday.",translation:"今天是星期三。"},
  {word:"Tuesday",phonetic:"/ˈtuːzdeɪ/",pos:"n.",meaning:"星期二",sentence:"Tuesday is my busy day.",translation:"周二是我忙碌的一天。"},
  {word:"Monday",phonetic:"/ˈmʌndeɪ/",pos:"n.",meaning:"星期一",sentence:"School starts on Monday.",translation:"周一开学。"},
  {word:"sun",phonetic:"/sʌn/",pos:"n.",meaning:"太阳",sentence:"The sun is shining.",translation:"太阳在照耀。"},
  {word:"city",phonetic:"/ˈsɪti/",pos:"n.",meaning:"城市",sentence:"I live in a big city.",translation:"我住在一个大城市。"},
  {word:"use",phonetic:"/juːz/",pos:"v.",meaning:"使用",sentence:"Can I use your phone?",translation:"我能用你的手机吗？"},
  {word:"apple",phonetic:"/ˈæpl/",pos:"n.",meaning:"苹果",sentence:"An apple a day keeps the doctor away.",translation:"一天一苹果，医生远离我。"},
  {word:"every day",phonetic:"/ˈevri deɪ/",pos:"phr.",meaning:"每天",sentence:"I exercise every day.",translation:"我每天锻炼。"},
  {word:"breakfast",phonetic:"/ˈbrekfəst/",pos:"n.",meaning:"早餐",sentence:"I eat eggs for breakfast.",translation:"我早餐吃鸡蛋。"},
  {word:"link",phonetic:"/lɪŋk/",pos:"n., v.",meaning:"链接，连接",sentence:"Click the link below.",translation:"点击下面的链接。"},
  {word:"eat",phonetic:"/iːt/",pos:"v.",meaning:"吃",sentence:"Let's eat dinner.",translation:"我们吃晚饭吧。"},
  {word:"rice",phonetic:"/raɪs/",pos:"n.",meaning:"米饭",sentence:"Asians eat a lot of rice.",translation:"亚洲人吃很多米饭。"},
  {word:"some",phonetic:"/sʌm/",pos:"adj., pron.",meaning:"一些",sentence:"I want some water.",translation:"我想要一些水。"},
  {word:"want",phonetic:"/wɑːnt/",pos:"v.",meaning:"想要",sentence:"I want a new car.",translation:"我想要一辆新车。"},
  {word:"bread",phonetic:"/bred/",pos:"n.",meaning:"面包",sentence:"I like fresh bread.",translation:"我喜欢新鲜面包。"},
  {word:"noodles",phonetic:"/ˈnuːdlz/",pos:"n.",meaning:"面条",sentence:"Beef noodles are delicious.",translation:"牛肉面很好吃。"},
  {word:"mice",phonetic:"/maɪs/",pos:"n.",meaning:"老鼠(复数)",sentence:"The cat chased the mice.",translation:"猫追赶老鼠。"},
  {word:"egg",phonetic:"/eɡ/",pos:"n.",meaning:"鸡蛋",sentence:"I boiled an egg.",translation:"我煮了一个鸡蛋。"},
  {word:"never",phonetic:"/ˈnevər/",pos:"adv.",meaning:"从不",sentence:"I never smoke.",translation:"我从不吸烟。"},
  {word:"vegetable",phonetic:"/ˈvedʒtəbl/",pos:"n.",meaning:"蔬菜",sentence:"Eat more vegetables.",translation:"多吃蔬菜。"},
  {word:"fruit",phonetic:"/fruːt/",pos:"n.",meaning:"水果",sentence:"Fresh fruit is healthy.",translation:"新鲜水果很健康。"},
  {word:"soup",phonetic:"/suːp/",pos:"n.",meaning:"汤",sentence:"The soup is hot.",translation:"汤很热。"},
  {word:"tomato",phonetic:"/təˈmeɪtoʊ/",pos:"n.",meaning:"西红柿",sentence:"I like tomato soup.",translation:"我喜欢番茄汤。"},
  {word:"potato",phonetic:"/pəˈteɪtoʊ/",pos:"n.",meaning:"土豆",sentence:"I like baked potatoes.",translation:"我喜欢烤土豆。"},
  {word:"seeds",phonetic:"/siːdz/",pos:"n.",meaning:"种子",sentence:"Plant the seeds in the soil.",translation:"把种子种在土里。"},
  {word:"read",phonetic:"/riːd/",pos:"v.",meaning:"阅读",sentence:"I read books every night.",translation:"我每晚读书。"},
  {word:"play",phonetic:"/pleɪ/",pos:"v.",meaning:"玩，演奏",sentence:"They play soccer.",translation:"他们踢足球。"},
  {word:"leader",phonetic:"/ˈliːdər/",pos:"n.",meaning:"领导者",sentence:"He is a good leader.",translation:"他是一个好的领导者。"},
  {word:"basketball",phonetic:"/ˈbæskɪtbɔːl/",pos:"n.",meaning:"篮球",sentence:"I play basketball.",translation:"我打篮球。"},
  {word:"tennis",phonetic:"/ˈtenɪs/",pos:"n.",meaning:"网球",sentence:"Tennis is a fun sport.",translation:"网球是一项有趣的运动。"},
  {word:"baseball",phonetic:"/ˈbeɪsbɔːl/",pos:"n.",meaning:"棒球",sentence:"Americans love baseball.",translation:"美国人喜爱棒球。"},
  {word:"does",phonetic:"/dʌz/",pos:"v.",meaning:"做(第三人称单数)",sentence:"He does his homework.",translation:"他做他的作业。"},
  {word:"every",phonetic:"/ˈevri/",pos:"adj.",meaning:"每一个",sentence:"Every student has a book.",translation:"每个学生都有一本书。"},
  {word:"noodle",phonetic:"/ˈnuːdl/",pos:"n.",meaning:"面条",sentence:"This noodle is long.",translation:"这根面条很长。"},
  {word:"movie",phonetic:"/ˈmuːvi/",pos:"n.",meaning:"电影",sentence:"Let's watch a movie.",translation:"我们看电影吧。"},
  {word:"draw",phonetic:"/drɔː/",pos:"v.",meaning:"画",sentence:"She likes to draw.",translation:"她喜欢画画。"},
  {word:"sing",phonetic:"/sɪŋ/",pos:"v.",meaning:"唱歌",sentence:"Can you sing a song?",translation:"你会唱首歌吗？"},
  {word:"music",phonetic:"/ˈmjuːzɪk/",pos:"n.",meaning:"音乐",sentence:"I listen to music.",translation:"我听音乐。"},
  {word:"cook",phonetic:"/kʊk/",pos:"v., n.",meaning:"烹饪，厨师",sentence:"My dad loves to cook.",translation:"我爸爸喜欢做饭。"},
  {word:"doesn't",phonetic:"/ˈdʌznt/",pos:"contr.",meaning:"不(does not)",sentence:"He doesn't like spicy food.",translation:"他不喜欢辣的食物。"},
  {word:"sometimes",phonetic:"/ˈsʌmtaɪmz/",pos:"adv.",meaning:"有时",sentence:"I sometimes walk to work.",translation:"我有时走路去上班。"},
  {word:"time",phonetic:"/taɪm/",pos:"n.",meaning:"时间",sentence:"What time is it?",translation:"几点了？"},
  {word:"fine",phonetic:"/faɪn/",pos:"adj.",meaning:"好的，健康的",sentence:"I am fine, thank you.",translation:"我很好，谢谢。"},
  {word:"usually",phonetic:"/ˈjuːʒuəli/",pos:"adv.",meaning:"通常",sentence:"I usually get up at 7.",translation:"我通常7点起床。"},
  {word:"train",phonetic:"/treɪn/",pos:"n.",meaning:"火车",sentence:"I take the train to work.",translation:"我坐火车去上班。"},
  {word:"airport",phonetic:"/ˈerpɔːrt/",pos:"n.",meaning:"机场",sentence:"We are going to the airport.",translation:"我们要去机场。"},
  {word:"station",phonetic:"/ˈsteɪʃn/",pos:"n.",meaning:"车站",sentence:"Meet me at the station.",translation:"在车站见我。"},
  {word:"the subway",phonetic:"/ðə ˈsʌbweɪ/",pos:"phr.",meaning:"地铁",sentence:"I take the subway.",translation:"我坐地铁。"},
  {word:"bathroom",phonetic:"/ˈbæθruːm/",pos:"n.",meaning:"浴室，洗手间",sentence:"May I use the bathroom?",translation:"我可以用一下洗手间吗？"},
  {word:"over there",phonetic:"/ˈoʊvər ðer/",pos:"phr.",meaning:"在那边",sentence:"Look over there.",translation:"看那边。"},
  {word:"where is",phonetic:"/wer ɪz/",pos:"phr.",meaning:"在哪里",sentence:"Where is the bank?",translation:"银行在哪里？"},
  {word:"over",phonetic:"/ˈoʊvər/",pos:"prep., adv.",meaning:"在...上方，结束",sentence:"Game over.",translation:"游戏结束。"},
  {word:"plane",phonetic:"/pleɪn/",pos:"n.",meaning:"飞机",sentence:"The plane is flying high.",translation:"飞机飞得很高。"},
  {word:"ticket",phonetic:"/ˈtɪkɪt/",pos:"n.",meaning:"票",sentence:"I have a movie ticket.",translation:"我有一张电影票。"},
  {word:"right",phonetic:"/raɪt/",pos:"adj., adv., n.",meaning:"正确的，右边",sentence:"Turn right at the corner.",translation:"在拐角处向右转。"},
  {word:"passport",phonetic:"/ˈpæspɔːrt/",pos:"n.",meaning:"护照",sentence:"Show me your passport.",translation:"出示你的护照。"},
  {word:"bus",phonetic:"/bʌs/",pos:"n.",meaning:"公共汽车",sentence:"The bus is late.",translation:"公交车晚点了。"},
  {word:"hotel",phonetic:"/hoʊˈtel/",pos:"n.",meaning:"旅馆",sentence:"We stayed at a hotel.",translation:"我们住在一家旅馆。"},
  {word:"ticket office",phonetic:"/ˈtɪkɪt ˈɔːfɪs/",pos:"n.",meaning:"售票处",sentence:"Go to the ticket office.",translation:"去售票处。"},
  {word:"port",phonetic:"/pɔːrt/",pos:"n.",meaning:"港口",sentence:"The ship is in the port.",translation:"船在港口。"},
  {word:"late",phonetic:"/leɪt/",pos:"adj., adv.",meaning:"晚的，迟的",sentence:"Don't be late.",translation:"别迟到。"},
  {word:"last",phonetic:"/læst/",pos:"adj., adv.",meaning:"最后的，上一个",sentence:"Last night was fun.",translation:"昨晚很有趣。"},
  {word:"closed",phonetic:"/kloʊzd/",pos:"adj.",meaning:"关闭的",sentence:"The store is closed.",translation:"商店关门了。"},
  {word:"what is",phonetic:"/wʌt ɪz/",pos:"phr.",meaning:"是什么",sentence:"What is your name?",translation:"你叫什么名字？"},
  {word:"guy",phonetic:"/ɡaɪ/",pos:"n.",meaning:"家伙，人",sentence:"He is a nice guy.",translation:"他是个好人。"},
  {word:"go shopping",phonetic:"/ɡoʊ ˈʃɑːpɪŋ/",pos:"phr.",meaning:"去购物",sentence:"Let's go shopping.",translation:"我们去购物吧。"},
  {word:"want to",phonetic:"/wɑːnt tu/",pos:"phr.",meaning:"想要",sentence:"I want to sleep.",translation:"我想睡觉。"},
  {word:"skirt",phonetic:"/skɜːrt/",pos:"n.",meaning:"裙子",sentence:"She is wearing a skirt.",translation:"她穿着一条裙子。"},
  {word:"jeans",phonetic:"/dʒiːnz/",pos:"n.",meaning:"牛仔裤",sentence:"I like blue jeans.",translation:"我喜欢蓝色牛仔裤。"},
  {word:"those",phonetic:"/ðoʊz/",pos:"pron.",meaning:"那些",sentence:"Those are my friends.",translation:"那些是我的朋友。"},
  {word:"t-shirt",phonetic:"/ˈtiːʃɜːrt/",pos:"n.",meaning:"T恤",sentence:"I bought a white t-shirt.",translation:"我买了一件白色T恤。"},
  {word:"different",phonetic:"/ˈdɪfrənt/",pos:"adj.",meaning:"不同的",sentence:"They have different ideas.",translation:"他们有不同的想法。"},
  {word:"store",phonetic:"/stɔːr/",pos:"n.",meaning:"商店",sentence:"The store opens at 9.",translation:"商店9点开门。"},
  {word:"clothes",phonetic:"/kloʊðz/",pos:"n.",meaning:"衣服",sentence:"I need new clothes.",translation:"我需要新衣服。"},
  {word:"clothes store",phonetic:"/kloʊðz stɔːr/",pos:"n.",meaning:"服装店",sentence:"She works in a clothes store.",translation:"她在一家服装店工作。"},
  {word:"open",phonetic:"/ˈoʊpən/",pos:"v., adj.",meaning:"打开，开着的",sentence:"Open the door.",translation:"打开门。"},
  {word:"hand",phonetic:"/hænd/",pos:"n.",meaning:"手",sentence:"Wash your hands.",translation:"洗手。"},
  {word:"often",phonetic:"/ˈɔːfn/",pos:"adv.",meaning:"经常",sentence:"I often read books.",translation:"我经常读书。"},
  {word:"wash",phonetic:"/wɑːʃ/",pos:"v.",meaning:"洗",sentence:"Wash your face.",translation:"洗脸。"},
  {word:"face",phonetic:"/feɪs/",pos:"n.",meaning:"脸",sentence:"She has a pretty face.",translation:"她有一张漂亮的脸。"},
  {word:"bed",phonetic:"/bed/",pos:"n.",meaning:"床",sentence:"Time for bed.",translation:"该睡觉了。"},
  {word:"grandma",phonetic:"/ˈɡrænmɑː/",pos:"n.",meaning:"奶奶，外婆",sentence:"My grandma is kind.",translation:"我奶奶很慈祥。"},
  {word:"grandpa",phonetic:"/ˈɡrænpɑː/",pos:"n.",meaning:"爷爷，外公",sentence:"My grandpa likes fishing.",translation:"我爷爷喜欢钓鱼。"},
  {word:"watches",phonetic:"/ˈwɑːtʃɪz/",pos:"n., v.",meaning:"手表(复数)，观看(三单)",sentence:"He watches TV every day.",translation:"他每天看电视。"},
  {word:"eye",phonetic:"/aɪ/",pos:"n.",meaning:"眼睛",sentence:"Close your eyes.",translation:"闭上眼睛。"},
  {word:"brown",phonetic:"/braʊn/",pos:"adj., n.",meaning:"棕色的，棕色",sentence:"She has brown eyes.",translation:"她有棕色的眼睛。"},
  {word:"hair",phonetic:"/her/",pos:"n.",meaning:"头发",sentence:"Her hair is long.",translation:"她的头发很长。"},
  {word:"when",phonetic:"/wen/",pos:"adv., conj.",meaning:"什么时候",sentence:"When is your birthday?",translation:"你的生日是什么时候？"},
  {word:"beef",phonetic:"/biːf/",pos:"n.",meaning:"牛肉",sentence:"I like roast beef.",translation:"我喜欢烤牛肉。"},
  {word:"would like to",phonetic:"/wʊd laɪk tu/",pos:"phr.",meaning:"想要",sentence:"I would like to go.",translation:"我想要去。"},
  {word:"food",phonetic:"/fuːd/",pos:"n.",meaning:"食物",sentence:"The food is delicious.",translation:"食物很美味。"},
  {word:"make",phonetic:"/meɪk/",pos:"v.",meaning:"制作",sentence:"I can make a cake.",translation:"我会做蛋糕。"},
  {word:"dinner",phonetic:"/ˈdɪnər/",pos:"n.",meaning:"晚餐",sentence:"Dinner is ready.",translation:"晚饭做好了。"},
  {word:"lunch",phonetic:"/lʌntʃ/",pos:"n.",meaning:"午餐",sentence:"Let's have lunch.",translation:"我们吃午饭吧。"},
  {word:"yesterday",phonetic:"/ˈjestərdeɪ/",pos:"adv., n.",meaning:"昨天",sentence:"I saw him yesterday.",translation:"我昨天看见了他。"},
  {word:"museum",phonetic:"/mjuˈziːəm/",pos:"n.",meaning:"博物馆",sentence:"The museum is closed today.",translation:"博物馆今天闭馆。"},
  {word:"still",phonetic:"/stɪl/",pos:"adv., adj.",meaning:"仍然，静止的",sentence:"Are you still here?",translation:"你还在这里吗？"},
  {word:"delicious",phonetic:"/dɪˈlɪʃəs/",pos:"adj.",meaning:"美味的",sentence:"This cake is delicious.",translation:"这蛋糕很美味。"},
  {word:"remember",phonetic:"/rɪˈmembər/",pos:"v.",meaning:"记得",sentence:"Please remember to call me.",translation:"请记得给我打电话。"},
  {word:"reason",phonetic:"/ˈriːzn/",pos:"n.",meaning:"原因，理由",sentence:"What is the reason?",translation:"理由是什么？"},
  {word:"visit",phonetic:"/ˈvɪzɪt/",pos:"v., n.",meaning:"参观，拜访",sentence:"I want to visit China.",translation:"我想去中国参观。"},
  {word:"hit",phonetic:"/hɪt/",pos:"v., n.",meaning:"打，击中",sentence:"The car hit the tree.",translation:"汽车撞到了树上。"},
  {word:"build",phonetic:"/bɪld/",pos:"v.",meaning:"修建，建筑",sentence:"They plan to build a new bridge.",translation:"他们计划修建一座新桥。"},
  {word:"government",phonetic:"/ˈɡʌvərnmənt/",pos:"n.",meaning:"政府",sentence:"The government passes laws.",translation:"政府通过法律。"},
  {word:"desert",phonetic:"/ˈdezərt/",pos:"n.",meaning:"沙漠",sentence:"It rarely rains in the desert.",translation:"沙漠里很少下雨。"},
  {word:"film",phonetic:"/fɪlm/",pos:"v., n.",meaning:"拍摄，电影",sentence:"They are filming a movie here.",translation:"他们正在这里拍摄电影。"},
  {word:"vase",phonetic:"/veɪs/",pos:"n.",meaning:"花瓶",sentence:"Put the flowers in the vase.",translation:"把花放进花瓶里。"},
  {word:"horse",phonetic:"/hɔːrs/",pos:"n.",meaning:"马",sentence:"He can ride a horse.",translation:"他会骑马。"},
  {word:"grass",phonetic:"/ɡræs/",pos:"n.",meaning:"草地，草",sentence:"The children are playing on the grass.",translation:"孩子们正在草地上玩耍。"},
  {word:"flower",phonetic:"/ˈflaʊər/",pos:"n.",meaning:"花",sentence:"What is your favorite flower?",translation:"你最喜欢什么花？"},
  {word:"chat",phonetic:"/tʃæt/",pos:"v., n.",meaning:"聊天",sentence:"We had a nice chat.",translation:"我们聊得很愉快。"},
  {word:"street",phonetic:"/striːt/",pos:"n.",meaning:"街道",sentence:"The street is busy.",translation:"这条街很热闹。"},
  {word:"walk",phonetic:"/wɔːk/",pos:"v., n.",meaning:"走，散步",sentence:"He is walking to school.",translation:"他正走着去学校。"},
  {word:"fan",phonetic:"/fæn/",pos:"n.",meaning:"粉丝，风扇",sentence:"I am a big fan of yours.",translation:"我是你的忠实粉丝。"},
  {word:"surround",phonetic:"/səˈraʊnd/",pos:"v.",meaning:"包围",sentence:"Trees surround the house.",translation:"树木包围着房子。"},
  {word:"charger",phonetic:"/ˈtʃɑːrdʒər/",pos:"n.",meaning:"充电器",sentence:"I need a phone charger.",translation:"我需要一个手机充电器。"},
  {word:"follow",phonetic:"/ˈfɑːloʊ/",pos:"v.",meaning:"跟随，跟着",sentence:"Follow me, please.",translation:"请跟着我。"},
  {word:"gift",phonetic:"/ɡɪft/",pos:"n.",meaning:"礼物",sentence:"This gift is for you.",translation:"这个礼物是给你的。"},
  {word:"receive",phonetic:"/rɪˈsiːv/",pos:"v.",meaning:"收到",sentence:"I received a letter.",translation:"我收到了一封信。"},
  {word:"window",phonetic:"/ˈwɪndoʊ/",pos:"n.",meaning:"窗户",sentence:"Open the window.",translation:"打开窗户。"},
  {word:"meet",phonetic:"/miːt/",pos:"v.",meaning:"见面，遇见",sentence:"Let's meet at 5.",translation:"我们5点见面吧。"},
  {word:"tree",phonetic:"/triː/",pos:"n.",meaning:"树",sentence:"The tree is green.",translation:"这棵树是绿色的。"},
  {word:"surgery",phonetic:"/ˈsɜːrdʒəri/",pos:"n.",meaning:"手术",sentence:"He needs surgery.",translation:"他需要做手术。"},
  {word:"keyboard",phonetic:"/ˈkiːbɔːrd/",pos:"n.",meaning:"键盘",sentence:"The keyboard is broken.",translation:"键盘坏了。"},
  {word:"socket",phonetic:"/ˈsɑːkɪt/",pos:"n.",meaning:"插座",sentence:"The socket is on the wall.",translation:"插座在墙上。"},
  {word:"rice cooker",phonetic:"/raɪs ˈkʊkər/",pos:"n.",meaning:"电饭煲",sentence:"Use the rice cooker to make rice.",translation:"用电饭煲煮饭。"},
  {word:"faucet",phonetic:"/ˈfɔːsɪt/",pos:"n.",meaning:"水龙头",sentence:"Turn off the faucet.",translation:"关掉水龙头。"},
  {word:"toilet",phonetic:"/ˈtɔɪlət/",pos:"n.",meaning:"马桶，厕所",sentence:"The toilet is clean.",translation:"马桶很干净。"},
  {word:"playground",phonetic:"/ˈpleɪɡraʊnd/",pos:"n.",meaning:"操场",sentence:"Kids play in the playground.",translation:"孩子们在操场上玩。"},
  {word:"location",phonetic:"/loʊˈkeɪʃn/",pos:"n.",meaning:"位置",sentence:"Send me your location.",translation:"把你的位置发给我。"},
  {word:"flexible",phonetic:"/ˈfleksəbl/",pos:"adj.",meaning:"灵活的",sentence:"My schedule is flexible.",translation:"我的时间表很灵活。"},
  {word:"handle",phonetic:"/ˈhændl/",pos:"v.",meaning:"处理",sentence:"I can handle it.",translation:"我能处理它。"},
  {word:"help",phonetic:"/help/",pos:"v., n.",meaning:"帮助",sentence:"Thanks for your help.",translation:"谢谢你的帮助。"},
  {word:"market",phonetic:"/ˈmɑːrkɪt/",pos:"n.",meaning:"市场",sentence:"I bought it at the market.",translation:"我在市场买的。"},
  {word:"early morning",phonetic:"/ˌɜːrli ˈmɔːrnɪŋ/",pos:"n.",meaning:"凌晨",sentence:"It happened in the early morning.",translation:"这发生在凌晨。"},
  {word:"answer",phonetic:"/ˈænsər/",pos:"v., n.",meaning:"回答",sentence:"Answer the question.",translation:"回答问题。"},
  {word:"homework",phonetic:"/ˈhoʊmwɜːrk/",pos:"n.",meaning:"作业",sentence:"Do your homework.",translation:"做你的作业。"},
  {word:"dance",phonetic:"/dæns/",pos:"v., n.",meaning:"跳舞",sentence:"Shall we dance?",translation:"我们跳舞好吗？"},
  {word:"bicycle",phonetic:"/ˈbaɪsɪkl/",pos:"n.",meaning:"自行车",sentence:"I ride a bicycle.",translation:"我骑自行车。"},
  {word:"brief",phonetic:"/briːf/",pos:"adj.",meaning:"短暂的",sentence:"We had a brief chat.",translation:"我们聊了一会儿。"},
  {word:"knife",phonetic:"/naɪf/",pos:"n.",meaning:"刀",sentence:"The knife is sharp.",translation:"刀很锋利。"},
  {word:"cancel",phonetic:"/ˈkænsl/",pos:"v.",meaning:"取消",sentence:"The flight was canceled.",translation:"航班被取消了。"},
  {word:"write",phonetic:"/raɪt/",pos:"v.",meaning:"写",sentence:"I write a diary every day.",translation:"我每天写日记。"},
  {word:"exercise",phonetic:"/ˈeksərsaɪz/",pos:"v., n.",meaning:"锻炼",sentence:"Exercise is good for health.",translation:"锻炼对健康有益。"},
  {word:"sport",phonetic:"/spɔːrt/",pos:"n.",meaning:"运动",sentence:"Football is a popular sport.",translation:"足球是一项流行的运动。"},
  {word:"sports meeting",phonetic:"/spɔːrts ˈmiːtɪŋ/",pos:"n.",meaning:"运动会",sentence:"The sports meeting starts tomorrow.",translation:"运动会明天开始。"},
  {word:"stadium",phonetic:"/ˈsteɪdiəm/",pos:"n.",meaning:"体育馆",sentence:"The concert is in the stadium.",translation:"演唱会在体育馆举行。"},
  {word:"library",phonetic:"/ˈlaɪbreri/",pos:"n.",meaning:"图书馆",sentence:"Quiet please, this is a library.",translation:"请安静，这里是图书馆。"},
  {word:"gym",phonetic:"/dʒɪm/",pos:"n.",meaning:"健身房",sentence:"He goes to the gym every day.",translation:"他每天去健身房。"},
  {word:"letter",phonetic:"/ˈletər/",pos:"n.",meaning:"信件",sentence:"I received a letter from him.",translation:"我收到了他的一封信。"},
  {word:"article",phonetic:"/ˈɑːrtɪkl/",pos:"n.",meaning:"文章",sentence:"Read this article clearly.",translation:"清楚地阅读这篇文章。"},
  {word:"submit",phonetic:"/səbˈmɪt/",pos:"v.",meaning:"提交",sentence:"Please submit your report.",translation:"请提交你的报告。"},
  {word:"report",phonetic:"/rɪˈpɔːrt/",pos:"n.",meaning:"报告",sentence:"The weather report says it will rain.",translation:"天气预报说会下雨。"},
  {word:"arrive",phonetic:"/əˈraɪv/",pos:"v.",meaning:"到达",sentence:"When will you arrive?",translation:"你什么时候到达？"},
  {word:"next",phonetic:"/nekst/",pos:"adj., adv.",meaning:"下一个",sentence:"Who is the next person?",translation:"下一个人是谁？"},
  {word:"foreigner",phonetic:"/ˈfɔːrənər/",pos:"n.",meaning:"外国人",sentence:"He is a foreigner here.",translation:"他在这里是个外国人。"},
  {word:"communicate",phonetic:"/kəˈmjuːnɪkeɪt/",pos:"v.",meaning:"交流",sentence:"We communicate by email.",translation:"我们通过邮件交流。"},
  {word:"strange",phonetic:"/streɪndʒ/",pos:"adj.",meaning:"奇怪的，奇",sentence:"That is a strange sound.",translation:"那是奇怪的声音。"},
  {word:"expect",phonetic:"/ɪkˈspekt/",pos:"v.",meaning:"期待",sentence:"I expect good results.",translation:"我期待好的结果。"},
  {word:"toothbrush",phonetic:"/ˈtuːθbrʌʃ/",pos:"n.",meaning:"牙刷",sentence:"I need a new toothbrush.",translation:"我需要一把新牙刷。"},
  {word:"year",phonetic:"/jɪr/",pos:"n.",meaning:"年",sentence:"Happy New Year!",translation:"新年快乐！"},
  {word:"match",phonetic:"/mætʃ/",pos:"n.",meaning:"比赛",sentence:"We won the match.",translation:"我们赢了这场比赛。"},
  {word:"grade",phonetic:"/ɡreɪd/",pos:"n.",meaning:"成绩，年级",sentence:"She got a good grade.",translation:"她取得了好成绩。"},
  {word:"project",phonetic:"/ˈprɑːdʒekt/",pos:"n.",meaning:"项目",sentence:"This is a big project.",translation:"这是一个大项目。"},
  {word:"witty",phonetic:"/ˈwɪti/",pos:"adj.",meaning:"机智的",sentence:"He gave a witty answer.",translation:"他给出了一个机智的回答。"},
  {word:"ending",phonetic:"/ˈendɪŋ/",pos:"n.",meaning:"结尾",sentence:"The movie has a happy ending.",translation:"这部电影有一个幸福的结尾。"},
  {word:"stage",phonetic:"/steɪdʒ/",pos:"n.",meaning:"阶段，舞台",sentence:"This is the first stage.",translation:"这是第一阶段。"},
  {word:"victory",phonetic:"/ˈvɪktəri/",pos:"n.",meaning:"胜利",sentence:"They celebrated their victory.",translation:"他们庆祝了他们的胜利。"},
  {word:"failure",phonetic:"/ˈfeɪljər/",pos:"n.",meaning:"失败",sentence:"Failure is the mother of success.",translation:"失败是成功之母。"},
  {word:"finish",phonetic:"/ˈfɪnɪʃ/",pos:"v.",meaning:"完成",sentence:"Finish your food.",translation:"吃完你的食物。"},
  {word:"plan",phonetic:"/plæn/",pos:"v., n.",meaning:"策划，计划",sentence:"We need to plan carefully.",translation:"我们需要仔细策划。"},
  {word:"organize",phonetic:"/ˈɔːrɡənaɪz/",pos:"v.",meaning:"整理，组织",sentence:"Organize your desk.",translation:"整理你的书桌。"},
  {word:"eraser",phonetic:"/ɪˈreɪsər/",pos:"n.",meaning:"橡皮",sentence:"Can I borrow your eraser?",translation:"我能借你的橡皮吗？"},
  {word:"resign",phonetic:"/rɪˈzaɪn/",pos:"v.",meaning:"辞职",sentence:"He decided to resign.",translation:"他决定辞职。"},
  {word:"classmate",phonetic:"/ˈklæsmeɪt/",pos:"n.",meaning:"同学",sentence:"She is my classmate.",translation:"她是我的同班同学。"},
  {word:"daily",phonetic:"/ˈdeɪli/",pos:"adj.",meaning:"日常的",sentence:"This is my daily routine.",translation:"这是我的日常惯例。"},
  {word:"notebook",phonetic:"/ˈnoʊtbʊk/",pos:"n.",meaning:"笔记本",sentence:"Write it in your notebook.",translation:"把它写在你的笔记本上。"},
  {word:"supermarket",phonetic:"/ˈsuːpərmɑːrkɪt/",pos:"n.",meaning:"超市",sentence:"I bought milk at the supermarket.",translation:"我在超市买了牛奶。"},
  {word:"describe",phonetic:"/dɪˈskraɪb/",pos:"v.",meaning:"描述",sentence:"Can you describe the thief?",translation:"你能描述一下小偷的样子吗？"},
  {word:"rule",phonetic:"/ruːl/",pos:"n.",meaning:"规则",sentence:"Follow the rules.",translation:"遵守规则。"},
  {word:"province",phonetic:"/ˈprɑːvɪns/",pos:"n.",meaning:"省份",sentence:"Which province are you from?",translation:"你来自哪个省份？"},
  {word:"cabinet",phonetic:"/ˈkæbɪnət/",pos:"n.",meaning:"柜子",sentence:" The cups are in the cabinet.",translation:"杯子在柜子里。"},
  {word:"dumpling",phonetic:"/ˈdʌmplɪŋ/",pos:"n.",meaning:"饺子",sentence:"I like to eat dumplings.",translation:"我喜欢吃饺子。"},
  {word:"ice cube",phonetic:"/aɪs kjuːb/",pos:"n.",meaning:"冰块",sentence:"Add an ice cube to my drink.",translation:"给我的饮料加块冰。"},
  {word:"toilet paper",phonetic:"/ˈtɔɪlət ˈpeɪpər/",pos:"n.",meaning:"卫生纸",sentence:"We are out of toilet paper.",translation:"我们没有卫生纸了。"},
  {word:"trade",phonetic:"/treɪd/",pos:"n., v.",meaning:"贸易",sentence:"International trade is important.",translation:"国际贸易很重要。"},
  {word:"sweater",phonetic:"/ˈswetər/",pos:"n.",meaning:"毛衣",sentence:"Put on your sweater.",translation:"穿上你的毛衣。"},
  {word:"sock",phonetic:"/sɑːk/",pos:"n.",meaning:"袜子",sentence:"I lost one sock.",translation:"我丢了一只袜子。"},
  {word:"lamp",phonetic:"/læmp/",pos:"n.",meaning:"灯",sentence:"Turn on the lamp.",translation:"把灯打开。"},
  {word:"frog",phonetic:"/frɔːɡ/",pos:"n.",meaning:"青蛙",sentence:"The frog jumps high.",translation:"青蛙跳得很高。"},
  {word:"teapot",phonetic:"/ˈtiːpɑːt/",pos:"n.",meaning:"茶壶",sentence:"The teapot is hot.",translation:"茶壶很烫。"},
  {word:"mango",phonetic:"/ˈmæŋɡoʊ/",pos:"n.",meaning:"芒果",sentence:"Mango is a tropical fruit.",translation:"芒果是热带水果。"},
  {word:"watermelon",phonetic:"/ˈwɔːtərmelən/",pos:"n.",meaning:"西瓜",sentence:"Watermelon is sweet.",translation:"西瓜很甜。"},
  {word:"printer",phonetic:"/ˈprɪntər/",pos:"n.",meaning:"打印机",sentence:"The printer is out of ink.",translation:"打印机没墨了。"},
  {word:"task",phonetic:"/tæsk/",pos:"n.",meaning:"任务",sentence:"Complete the task.",translation:"完成任务。"},
  {word:"boss",phonetic:"/bɔːs/",pos:"n.",meaning:"老板",sentence:"He is the boss.",translation:"他是老板。"},
  {word:"manager",phonetic:"/ˈmænɪdʒər/",pos:"n.",meaning:"经理",sentence:"I want to see the manager.",translation:"我想见经理。"},
  {word:"experience",phonetic:"/ɪkˈspɪriəns/",pos:"n.",meaning:"经历，经验",sentence:"She has a lot of experience.",translation:"她有很多经验。"},
  {word:"economy",phonetic:"/ɪˈkɑːnəmi/",pos:"n.",meaning:"经济",sentence:"The economy is growing.",translation:"经济正在增长。"},
  {word:"internship",phonetic:"/ˈɪntɜːrnʃɪp/",pos:"n.",meaning:"实习",sentence:"I am doing an internship.",translation:"我正在实习。"},
  {word:"scene",phonetic:"/siːn/",pos:"n.",meaning:"场景",sentence:"The scene was beautiful.",translation:"那个场景很美。"},
  {word:"fish",phonetic:"/fɪʃ/",pos:"n.",meaning:"鱼",sentence:"Fish swim in the water.",translation:"鱼在水里游。"},
  {word:"message",phonetic:"/ˈmesɪdʒ/",pos:"n.",meaning:"消息",sentence:"Leave a message.",translation:"留个口信。"},
  {word:"wait",phonetic:"/weɪt/",pos:"v.",meaning:"等待",sentence:"Wait for me.",translation:"等等我。"},
  {word:"delivery",phonetic:"/dɪˈlɪvəri/",pos:"n.",meaning:"配送，快递",sentence:"Free delivery on orders over $50.",translation:"满50美元免配送费。"},
  {word:"take a photo",phonetic:"/teɪk ə ˈfoʊtoʊ/",pos:"phr.",meaning:"拍照",sentence:"Can you take a photo of us?",translation:"你能帮我们拍张照吗？"},
  {word:"lively",phonetic:"/ˈlaɪvli/",pos:"adj.",meaning:"热闹的",sentence:"The party is very lively.",translation:"派对很热闹。"},
  {word:"cheap",phonetic:"/tʃiːp/",pos:"adj.",meaning:"便宜的",sentence:"This shirt is cheap.",translation:"这件衬衫很便宜。"},
  {word:"shift",phonetic:"/ʃɪft/",pos:"n., v.",meaning:"偏移，移动",sentence:"There was a shift in policy.",translation:"政策发生了偏移（改变）。"},
  {word:"habit",phonetic:"/ˈhæbɪt/",pos:"n.",meaning:"习惯",sentence:"Reading is a good habit.",translation:"阅读是个好习惯。"},
  {word:"get used to",phonetic:"/ɡet juːzd tu/",pos:"phr.",meaning:"习惯于",sentence:"I will get used to it.",translation:"我会习惯的。"},
  {word:"revise",phonetic:"/rɪˈvaɪz/",pos:"v.",meaning:"修改",sentence:"Please revise your essay.",translation:"请修改你的文章。"},
  {word:"cover",phonetic:"/ˈkʌvər/",pos:"v.",meaning:"覆盖",sentence:"Snow covered the ground.",translation:"雪覆盖了地面。"},
  {word:"deskmate",phonetic:"/ˈdeskməɪt/",pos:"n.",meaning:"同桌",sentence:"He is my deskmate.",translation:"他是我的同桌。"},
  {word:"stairs",phonetic:"/sterz/",pos:"n.",meaning:"楼梯",sentence:"Walk up the stairs.",translation:"走上楼梯。"},
  {word:"earthquake",phonetic:"/ˈɜːrθkweɪk/",pos:"n.",meaning:"地震",sentence:"The earthquake was strong.",translation:"地震很强烈。"},
  {word:"holiday",phonetic:"/ˈhɑːlədeɪ/",pos:"n.",meaning:"假期，放假",sentence:"I am on holiday.",translation:"我在放假。"},
  {word:"afraid",phonetic:"/əˈfreɪd/",pos:"adj.",meaning:"害怕的",sentence:"Don't be afraid.",translation:"别害怕。"},
  {word:"go home",phonetic:"/ɡoʊ hoʊm/",pos:"phr.",meaning:"回家",sentence:"I want to go home.",translation:"我想回家。"},
  {word:"pity",phonetic:"/ˈpɪti/",pos:"n.",meaning:"可惜，遗憾",sentence:"It's a pity you can't come.",translation:"你不能来真可惜。"},
  {word:"chance",phonetic:"/tʃæns/",pos:"n.",meaning:"机会",sentence:"Give me a chance.",translation:"给我一个机会。"},
  {word:"situation",phonetic:"/ˌsɪtʃuˈeɪʃn/",pos:"n.",meaning:"情况",sentence:"The situation is difficult.",translation:"情况很困难。"},
  {word:"feeling",phonetic:"/ˈfiːlɪŋ/",pos:"n.",meaning:"感觉",sentence:"I have a good feeling about this.",translation:"我对这件事感觉很好。"},
  {word:"neighbor",phonetic:"/ˈneɪbər/",pos:"n.",meaning:"邻居",sentence:"My neighbor is very friendly.",translation:"我的邻居非常友好。"},
  {word:"traffic",phonetic:"/ˈtræfɪk/",pos:"n.",meaning:"交通",sentence:"There is heavy traffic on the road.",translation:"路上的交通很拥堵。"},
  {word:"meeting room",phonetic:"/ˈmiːtɪŋ ruːm/",pos:"n.",meaning:"会议室",sentence:"We are waiting in the meeting room.",translation:"我们在会议室等待。"},
  {word:"dictionary",phonetic:"/ˈdɪkʃəneri/",pos:"n.",meaning:"字典",sentence:"Please look up the word in the dictionary.",translation:"请在字典里查这个单词。"},
  {word:"weather",phonetic:"/ˈweðər/",pos:"n.",meaning:"天气",sentence:"The weather is nice today.",translation:"今天天气很好。"},
  {word:"mountain",phonetic:"/ˈmaʊntn/",pos:"n.",meaning:"山",sentence:"They climbed the mountain yesterday.",translation:"他们昨天爬了山。"},
  {word:"river",phonetic:"/ˈrɪvər/",pos:"n.",meaning:"河",sentence:"The river flows into the sea.",translation:"这条河流入大海。"},
  {word:"machine",phonetic:"/məˈʃiːn/",pos:"n.",meaning:"机器",sentence:"This machine is very easy to use.",translation:"这台机器很容易使用。"},
  {word:"video games",phonetic:"/ˈvɪdiəʊ ɡeɪmz/",pos:"n.",meaning:"电子游戏",sentence:"He loves playing video games.",translation:"他喜欢玩电子游戏。"},
  {word:"weekend",phonetic:"/ˌwiːkˈend/",pos:"n.",meaning:"周末",sentence:"What are you doing this weekend?",translation:"你这个周末做什么？"},
  {word:"dishes",phonetic:"/ˈdɪʃɪz/",pos:"n.",meaning:"碗碟",sentence:"It is my turn to wash the dishes.",translation:"轮到我洗碗了。"},
  {word:"lake",phonetic:"/leɪk/",pos:"n.",meaning:"湖",sentence:"They went fishing by the lake.",translation:"他们去湖边钓鱼了。"},
  {word:"kitchen",phonetic:"/ˈkɪtʃɪn/",pos:"n.",meaning:"厨房",sentence:"My mother is cooking in the kitchen.",translation:"我妈妈正在厨房做饭。"},
  {word:"museums",phonetic:"/mjuˈziːəmz/",pos:"n.",meaning:"博物馆",sentence:"We visited many museums in London.",translation:"我们在伦敦参观了很多博物馆。"},
  {word:"package",phonetic:"/ˈpækɪdʒ/",pos:"n.",meaning:"包裹",sentence:"I received a package from my friend.",translation:"我收到了朋友寄来的包裹。"},
  {word:"software",phonetic:"/ˈsɒftweər/",pos:"n.",meaning:"软件",sentence:"You need to update your software.",translation:"你需要更新你的软件。"},
  {word:"lawyer",phonetic:"/ˈlɔːjər/",pos:"n.",meaning:"律师",sentence:"She wants to become a lawyer.",translation:"她想成为一名律师。"},
  {word:"Europe",phonetic:"/ˈjʊərəp/",pos:"n.",meaning:"欧洲",sentence:"They traveled around Europe last summer.",translation:"去年夏天他们环游了欧洲。"},
  {word:"invite",phonetic:"/ɪnˈvaɪt/",pos:"v.",meaning:"邀请",sentence:"I will invite him to my birthday party.",translation:"我会邀请他参加我的生日派对。"},
  {word:"tell",phonetic:"/tel/",pos:"v.",meaning:"告诉",sentence:"Can you tell me the truth?",translation:"你能告诉我真相吗？"},
  {word:"say",phonetic:"/seɪ/",pos:"v.",meaning:"说",sentence:"What did you say?",translation:"你说了什么？"},
  {word:"fix",phonetic:"/fɪks/",pos:"v.",meaning:"修理",sentence:"Can you help me fix my bike?",translation:"你能帮我修自行车吗？"},
  {word:"run",phonetic:"/rʌn/",pos:"v.",meaning:"跑",sentence:"He can run very fast.",translation:"他能跑得很快。"},
  {word:"climb",phonetic:"/klaɪm/",pos:"v.",meaning:"攀爬",sentence:"Monkeys can climb trees easily.",translation:"猴子能轻易地爬树。"},
  {word:"swim",phonetic:"/swɪm/",pos:"v.",meaning:"游泳",sentence:"I learned to swim when I was five.",translation:"我五岁时学会了游泳。"},
  {word:"must",phonetic:"/mʌst/",pos:"aux.",meaning:"必须",sentence:"You must stop at the red light.",translation:"红灯时你必须停下。"},
  {word:"skate",phonetic:"/skeɪt/",pos:"v.",meaning:"滑冰",sentence:"Let's go skate on the ice.",translation:"我们去冰上滑冰吧。"},
  {word:"travel",phonetic:"/ˈtrævl/",pos:"v.",meaning:"旅行",sentence:"I love to travel to new places.",translation:"我喜欢去新的地方旅行。"},
  {word:"clean",phonetic:"/kliːn/",pos:"v.",meaning:"打扫",sentence:"Please clean your room.",translation:"请打扫你的房间。"},
  {word:"worry",phonetic:"/ˈwʌri/",pos:"v.",meaning:"担心",sentence:"Don't worry about the test.",translation:"别担心那个考试。"},
  {word:"healthy",phonetic:"/ˈhelθi/",pos:"adj.",meaning:"健康的",sentence:"Vegetables are healthy food.",translation:"蔬菜是健康食品。"},
  {word:"dangerous",phonetic:"/ˈdeɪndʒərəs/",pos:"adj.",meaning:"危险的",sentence:"It is dangerous to play with fire.",translation:"玩火是危险的。"},
  {word:"interesting",phonetic:"/ˈɪntrəstɪŋ/",pos:"adj.",meaning:"有趣的",sentence:"This book is very interesting.",translation:"这本书很有趣。"},
  {word:"out of order",phonetic:"/aʊt əv ˈɔːrdər/",pos:"phrase",meaning:"故障",sentence:"The elevator is out of order.",translation:"电梯坏了。"},
  {word:"early",phonetic:"/ˈɜːrli/",pos:"adj.",meaning:"早的",sentence:"He arrived early for the meeting.",translation:"他开会早到了。"},
  {word:"sad",phonetic:"/sæd/",pos:"adj.",meaning:"悲伤的",sentence:"The movie has a sad ending.",translation:"这部电影有一个悲伤的结局。"},
  {word:"spicy",phonetic:"/ˈspaɪsi/",pos:"adj.",meaning:"辛辣的",sentence:"I like spicy food.",translation:"我喜欢吃辣的食物。"},
  {word:"hungry",phonetic:"/ˈhʌŋɡri/",pos:"adj.",meaning:"饥饿的",sentence:"I am so hungry, let's eat.",translation:"我好饿，我们吃饭吧。"},
  {word:"icy",phonetic:"/ˈaɪsi/",pos:"adj.",meaning:"结冰的",sentence:"The roads are icy and slippery.",translation:"路面结冰了，很滑。"},
  {word:"angry",phonetic:"/ˈæŋɡri/",pos:"adj.",meaning:"生气的",sentence:"Don't be angry with me.",translation:"别生我的气。"},
  {word:"quiet",phonetic:"/ˈkwaɪət/",pos:"adj.",meaning:"安静的",sentence:"Please keep quiet in the library.",translation:"在图书馆请保持安静。"},
  {word:"dirty",phonetic:"/ˈdɜːrti/",pos:"adj.",meaning:"脏的",sentence:"Your shoes are very dirty.",translation:"你的鞋子很脏。"},
  {word:"excellent",phonetic:"/ˈeksələnt/",pos:"adj.",meaning:"优秀的",sentence:"She did an excellent job.",translation:"她工作做得非常出色。"},
  {word:"easily",phonetic:"/ˈiːzəli/",pos:"adv.",meaning:"容易地",sentence:"He passed the test easily.",translation:"他轻松地通过了考试。"},
  {word:"alone",phonetic:"/əˈləʊn/",pos:"adj.",meaning:"独自的",sentence:"He lives alone in a big house.",translation:"他独自住在一个大房子里。"},
  {word:"quietly",phonetic:"/ˈkwaɪətli/",pos:"adv.",meaning:"安静地",sentence:"She sat quietly in the corner.",translation:"她安静地坐在角落里。"},
  {word:"thoroughly",phonetic:"/ˈθɜːrəli/",pos:"adv.",meaning:"彻底地",sentence:"Clean the room thoroughly.",translation:"彻底打扫房间。"},
  {word:"even",phonetic:"/ˈiːvn/",pos:"adv.",meaning:"甚至",sentence:"Even a child knows that.",translation:"甚至连小孩都知道那个。"},
  {word:"more easily",phonetic:"/mɔːr ˈiːzəli/",pos:"phrase",meaning:"更容易地",sentence:"With practice, you can do it more easily.",translation:"通过练习，你可以更容易地做到。"},
  {word:"Although",phonetic:"/ɔːlˈðəʊ/",pos:"conj.",meaning:"虽然",sentence:"Although it rained, we went out.",translation:"虽然下雨了，我们还是出去了。"},
  {word:"Because",phonetic:"/bɪˈkəz/",pos:"conj.",meaning:"因为",sentence:"I stayed home because I was sick.",translation:"我因为生病待在家里。"},
  {word:"Even if",phonetic:"/ˈiːvn ɪf/",pos:"conj.",meaning:"即使",sentence:"I will go even if it rains.",translation:"即使下雨我也要去。"},
  {word:"After",phonetic:"/ˈæftər/",pos:"prep.",meaning:"在...之后",sentence:"We can play after dinner.",translation:"晚饭后我们可以玩。"},
  {word:"Before",phonetic:"/bɪˈfɔːr/",pos:"prep.",meaning:"在...之前",sentence:"Finish your work before you leave.",translation:"在你离开前完成工作。"}
];

